### ISSUE TITLE
Some BaseController.GetControllerElementPath implementations return null

### ISSUE THREAD

**Issue by BHSPitMonkey** [ExtendRealityLtd/VRTK#1848] opened 2018-07-04 10:15 UTC
### Environment

 * Source of VRTK: GitHub
 * Version of VRTK: master d88c9eafc31975bb9566e5747c12e48e5f75fa3d (HEAD as of writing)
 * Version of Unity3D: Unity 2018.2.0 betas (all so far, up to at least b11)
 * Hardware used: Oculus Rift
 * SDK used: Oculus

### Steps to reproduce

(Not exactly applicable; See below)

### Expected behavior

All SDKs' implementations of `BaseController.GetControllerElementPath` always return a string, even if empty, like the Unity XR SDK:

https://github.com/thestonefox/VRTK/blob/110d22c6610496db94a1b8402524fd6a9a997031/Assets/VRTK/Source/SDK/Unity/SDK_UnityController.cs#L178-L186

### Current behavior

Some SDK implementations, such as Oculus, SteamVR, and the Simulator, will return `null` in certain cases:

https://github.com/thestonefox/VRTK/blob/23646281260b267250117eece6087e2181aadd4b/Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs#L156-L177

### Impact

Due to [a bug](https://fogbugz.unity3d.com/default.asp?1056406_0i9j51rmi457ci6v) that exists in the current pre-releases of Unity 2018.2 (still present in today's b11 release), `Transform.Find` will crash the engine/editor when passed null instead of a string. `VRTK_UIPointer.GetPointerOriginTransform` passes the result of `GetControllerElementPath` along to `Transform.Find`, eliciting this crash when the Controller SDK decides to return `null` in these cases.

Although this particular bug should be fixed by Unity, these Controller SDK implementations should still be made consistent anyway and always return a valid string.

**Comment by thestonefox** [comment] 2019-03-30 11:19
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:19 UTC
