### ISSUE TITLE
Height Adjust Teleport Add Slope Control (Walking up walls/terrain)

### ISSUE THREAD

**Issue by ChillyMcChillson** [ExtendRealityLtd/VRTK#746] opened 2016-12-08 07:49 UTC
I am able to walk up walls by walking into them, no way to control how steep climbable slope is 

Example https://youtu.be/xqyLNCOGpiM

**Comment by thestonefox** [comment] 2016-12-08 08:05
As spoke about in slack, fix will come soon, after the super breaking PR :)

But for others who want a quick work around, you can use fake box colliders at the base of the slopes to prevent the height adjust teleporter teleporting you straight up.

**Comment by thestonefox** [comment] 2016-12-08 08:06
Also, worth nothing, after the super breaking PR, this will be an issue with the Body Physics script.

**Comment by thestonefox** [comment] 2019-03-30 11:15
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:15 UTC
Labels: bug, w_bug

**Comment by sarahjoyl** [comment] 2020-06-17 18:10
I am still having this problem. How can i make a player slide or fall down slopes, based on the steepness?

**Comment by bddckr** [comment] 2020-06-18 07:46
If you have a bugreport and can follow the issue template this is the right place. For troubleshooting help please ask the 10k+ big community at https://www.vrtk.io/community.html
