### ISSUE TITLE
Pointer objects can be seen at Origin for 1 frame when disabling/enabling pointer

### ISSUE THREAD

**Issue by codemonkeynorth** [ExtendRealityLtd/VRTK#1776] opened 2018-04-27 01:28 UTC
as per https://github.com/thestonefox/VRTK/issues/1587#issuecomment-384485983

Pointer rays & (colliders?) render at origin for 1 frame before they are attached to the controllers

(Update: is it actually necessary to disable and enable the pointer anymore?)

### Steps to reproduce

1) open `LegacyExamples/003_ControllerSimplerPointer.unity`
2) disable the "Floor" object
3) add a sphere at `0,0,5`

On `LeftController`

4) set `Activation Button` to `Undefined` 
5) Uncheck `Hold button to activate`
6) Check `Activate on Enable`
7) (optional) Check `Cursor Distance Rescale` (to be able to see the pointer better)
8) add the script below to a GameObject and drag the `LeftController` onto the `Left Controller` inspector slot.

9) Run the scene
10) Note that when you press `A` button a green pointer can be seen firing from the origin for 1 frame, rather than the position of the controller

(Note also if you set `Tracer Visibility` to `Always On` on the `VRTK_StraightPointerRenderer` then a white cube can also seen at Origin)

### Expected behavior

The pointer beam should only fire from the controller and no objects should be seen at the origin

### Current behavior

Pointer beam is firing from the origin for 1 frame (and other objects can be seen like a white cube)

### Required Script
(attach to LeftController or anywhere)
```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using VRTK;
public class PointerTest2 : MonoBehaviour {

    public GameObject LeftController;

    private VRTK_Pointer leftPointer;
    private VRTK_StraightPointerRenderer leftPointerRenderer;
    private VRTK_ControllerEvents leftControllerEvents;


    private void Awake()
    {
        leftPointer = LeftController.GetComponent<VRTK_Pointer>();
        leftPointerRenderer = LeftController.GetComponent<VRTK_StraightPointerRenderer>();
        leftControllerEvents = LeftController.GetComponent<VRTK_ControllerEvents>();
    }

    private void OnEnable()
    {
        leftControllerEvents.ButtonOnePressed += Button1Pressed;
    }

    private void OnDisable()
    {
        leftControllerEvents.ButtonOnePressed -= Button1Pressed;
    }


    public void Button1Pressed(object sender, ControllerInteractionEventArgs e)
    {
       // as per Stonefox instructions @ https://github.com/thestonefox/VRTK/issues/1587#issuecomment-342452910

        DisablePointer();
        leftPointerRenderer.maximumLength = 120f;
        EnablePointer();
    }

    private void DisablePointer()
    {
        leftPointer.enabled = false;
        leftPointerRenderer.enabled = false;
    }

    private void EnablePointer()
    {
        leftPointerRenderer.enabled = true;
        leftPointer.enabled = true;
    }


}
```

### Environment

 * Source of VRTK: Github
 * Version of VRTK: master
 * Version of Unity3D: 2017.3.1.f1
 * Hardware used: Oculus
 * SDK uses: OculusVR

**Comment by codemonkeynorth** [comment] 2018-04-27 01:30
actual position of pointers
![actual-pointers](https://user-images.githubusercontent.com/20189985/39339886-ea4ebec6-49c2-11e8-86f8-023132bdb5b0.jpg)

beam rendering from origin for 1 frame
![pointer-origin-ray](https://user-images.githubusercontent.com/20189985/39339887-ea6c056c-49c2-11e8-9543-6d093f489a38.jpg)

**Comment by codemonkeynorth** [comment] 2018-04-27 01:45
white cube appearing for 1 frame when `tracer visibility` set to to `always on`
![white-cube-tracer-visibility-always-on](https://user-images.githubusercontent.com/20189985/39340261-10ec60cc-49c5-11e8-8c68-575f8035ce2a.jpg)

**Comment by thestonefox** [comment] 2019-04-02 07:30
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:30 UTC
Labels: unconfirmed bug
