### ISSUE TITLE
VRTK_ObjectFollow.targetPosition never initialized

### ISSUE THREAD

**Issue by rockwalrus** [ExtendRealityLtd/VRTK#1868] opened 2018-08-08 20:55 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github

 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0 (d88c9eafc31975bb9566e5747c12e48e5f75fa3d)

 * Version of Unity3D (e.g. Unity 5.4.4f1)
2018.1.1f1

 * Hardware used (e.g. Vive/Oculus)
Samsung Odyssey

 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
WMR

### Steps to reproduce

Create two objects sufficiently far from (0,0,0) and from each other.  Attach a VRTK_TransformFollow to one of the objects and set it to follow the other. Set Follows Position and Smooths Position. Set Max Allowed Per Frame to a large enough value, such as 100.

### Expected behavior

The following object should move smoothly from its initial location to the followed object.

### Current behavior

The following object jumps to (0,0,0) and then moves from there smoothly to the followed object. This is because VRTK_ObjectFollow.targetPosition is never initialized and so it defaults to (0,0,0).

**Comment by bddckr** [comment] 2018-08-09 18:09
A PR to set the various `target*` variables to the current state of the target in `OnEnable` is welcome!

**Comment by thestonefox** [comment] 2019-03-30 11:17
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:17 UTC
