### ISSUE TITLE
OnTouch event called on wrong InteractableObject

### ISSUE THREAD

**Issue by blackmoron** [ExtendRealityLtd/VRTK#1694] opened 2018-01-10 14:59 UTC
### Environment

 * Source of VRTK Unity Asset Store
 * Version of VRTK 3.2.1
 * Version of Unity3D 2017.3.0f3
 * Hardware used None
 * SDK used Simulator
 
### Steps to reproduce
* select example scene 041_Controller_ObjectSnappingToDropZones.unity
* add VRTK_InteractableObject_UnityEvents to the cube Cube_HighlightOnTouch
* create script Logger
```
using UnityEngine;

public class Logger : MonoBehaviour {

    public void LogName()
    {
        Debug.Log(this.name);
    }
	
}
```
* attach Logger script to the cube Cube_HighlightOnTouch
* add LogName function to OnTouch event
* duplicate Cube_HighlightOnTouch 4 times and create hierarchy original-> copy 1-> copy 2-> copy 3-> copy 4
* set y position of all duplicates to 1.1
* run
* touch cubes from top to down and repeat this action

### Expected behavior

Cube name logged in console will be the same as the name of the touched cube

### Current behavior

Logged name is not the name of touched cube but the name of its parent

### Other info

* probably related to https://github.com/thestonefox/VRTK/issues/983 since reverting fix proposed in link above will fix my issue but OnTouch will be again called per frame
* ignore bad highlighting, it is caused by:
```
foreach (Renderer renderer in GetComponentsInChildren<Renderer>(true))
{
	var objectReference = renderer.gameObject.GetInstanceID().ToString();
	if (!originalRendererMaterials.ContainsKey(objectReference))
	{
		continue;
	}

	renderer.materials = originalRendererMaterials[objectReference];
	renderer.sharedMaterials = originalSharedRendererMaterials[objectReference];
}
```
in VRTK_MaterialColorSwapHighlighter which should be reconsidered as well

**Comment by blackmoron** [comment] 2018-01-10 15:16
same on https://github.com/thestonefox/VRTK/tree/release/3.3.0-alpha

**Comment by blackmoron** [comment] 2018-01-11 06:58
this behavior seems to be fixed by https://github.com/thestonefox/VRTK/issues/1618 when you select MultiTouchSelectionStyle to ClosestOrigin

**Comment by thestonefox** [comment] 2019-04-02 07:34
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:34 UTC
Labels: unconfirmed bug, w_bug
