### ISSUE TITLE
Grab to Pointer Tip and Controller Grab goes crazy when overlapping

### ISSUE THREAD

**Issue by captaincrunchyourface** [ExtendRealityLtd/VRTK#1134] opened 2017-04-23 20:55 UTC
* Source of VRTK (Unity Asset Store or Github)
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
dcd69452ec2f2daade5654510263910c7ef978a1
 * Version of Unity3D (e.g. Unity 5.4.4f1)
Unity 5.6.0
 * Hardware used (e.g. Vive/Oculus)
Oculus
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR

### Steps to reproduce

Turn on "Grab to Pointer Tip".
Have pointers on, but grab with controller.

### Expected behavior

Grabbed object should stick to controller.

### Current behavior

Grabbed object moves around all over the place.

####
I made a quick patch in VRTK_BasePointerRenderer.cs in FixedUpdate()

if (controllingPointer && controllingPointer.interactWithObjects && objectInteractor && objectInteractor.activeInHierarchy && !controllerGrabScript.GetGrabbedObject())

Doesn't completely solve the issue, but the behavior is much better.

**Comment by thestonefox** [comment] 2017-04-26 12:57
i'm currently struggling to think of a good solution for this.

The problem is the pointer tip is an extended part of the controller, so when the tip is touching something then the controller is touching something. Which means if you touch something with the pointer tip then touch something with the controller, it already thinks the controller is touching the object.

**Comment by bddckr** [comment] 2017-04-30 18:25
Perhaps we could remember at grab-start whether the pointer tip or the controller itself was grabbing (colliding)? We would need to somehow prioritize one over the other in case both collide with the grabbed object, but this could be a setting on the pointer I guess.
From then on the remembered object would be used to position the grabbed object.

**Comment by thestonefox** [comment] 2017-04-30 18:57
We don't know what part is colliding because it's a trigger collider and the rigidbody is on the top level controller component and the controller colliders are children along with the pointer tip (which just has it's position updated every frame).

So we only know the controller is touching. The best we can do is know the pointer is active or not.

My thoughts are:

If you have `grab to pointer tip` ticked and the pointer is active then it should grab to the pointer tip, problem then lies though when you put the pointer tip inside the object along with the controller and grab, it just fires it off

**Comment by pnguyen2232** [comment] 2017-06-01 23:50
Hi @thestonefox ,

I was playing with version 3.1.0, and having the the grab to pointer tip option unchecked would make the object teleport to the controller and then stay on the controller for as long as the grabbing button was pressed. However when the grab to pointer tip is ticked, the object moves to the controller and then teleports back to the pointer after it touches the controller and then repeats. I was wondering if this was fixed in 3.2.0?

**Comment by thestonefox** [comment] 2017-06-02 04:53
@pnguyen2232 are you raising a new issue or is your issue the same as the one that was originally raised?

If you have a new issue then raise a new ticket. Also, there is no promise anything will be fixed for 3.2.0. The only things that are guaranteed to be fixed (by me) are the things that are already fixed. If you can find a fix yourself and raise a PR and it gets merged in before 3.2.0 release then that can also guarantee the fix being in the next release.

**Comment by thestonefox** [comment] 2019-03-30 11:15
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:15 UTC
Labels: bug, w_bug
