### ISSUE TITLE
Crash in VRTK_SharedMethods.GetNestedType

### ISSUE THREAD

**Issue by rockwalrus** [ExtendRealityLtd/VRTK#1860] opened 2018-08-01 19:26 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github

 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0 (hash not available)

 * Version of Unity3D (e.g. Unity 5.4.4f1)
2018.1.1f1

 * Hardware used (e.g. Vive/Oculus)
Samsung Odyssey

 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
Windows Mixed Reality, SteamVR

### Steps to reproduce

Create a scene that includes the WMR and the SteamVR SDK setups. Do a UWP build.

### Expected behavior

Since Unity doesn't support SteamVR on UWP, the SteamVR SDK setup should be disabled, just like the WMR SDK is disabled for a standalone build.

### Current behavior

The SteamVR SDK makes a call to VRTK_SharedMethods.GetNestedType, which has some UWP-specific code. Under some conditions we haven't been able to narrow down, `givenType.GetTypeInfo().GetDeclaredNestedType(name)` will return `null`, which is then immediately dereferenced, causing VRTK initialization to fail, the headset to display only black, and the audio output to be silent.

**Comment by thestonefox** [comment] 2019-03-30 11:18
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:18 UTC
