### ISSUE TITLE
[UI] When hover the button of scrollview, The color of button couldn't be changed

### ISSUE THREAD

**Issue by BensonZheng2016** [ExtendRealityLtd/VRTK#1709] opened 2018-01-19 04:28 UTC
### Environment

 * Source of VRTK (Github )
 * Version of VRTK (3.3.0-alpha) (6cb308689b6d786ad62f28bb7e34ca8dec1f6018)
 * Version of Unity3D (2017.1.0f3)
 * Hardware used (Oculus)
 * SDK used (Oculus Utilities)

### Steps to reproduce
1.Open 034_Controls_InteractingWithUnityUI scene.
2. Change "RightController" game object as follow
![image](https://user-images.githubusercontent.com/18454958/35134797-9999a7c6-fd13-11e7-9fe4-275cf843be50.png)
![image](https://user-images.githubusercontent.com/18454958/35134804-abb2f6ba-fd13-11e7-8054-7de935022d80.png)
### Expected behavior
When pointer hover the button of scrollview, The color of button will be changed.
![image](https://user-images.githubusercontent.com/18454958/35134863-3247ee24-fd14-11e7-977a-8e67b33707ac.png)

**Comment by BensonZheng2016** [comment] 2018-01-19 06:37
The bug will be occur on commint bc02cfae0218aa93a9fc740d36aece1cdcdd164f

**Comment by Tom-LeFx** [comment] 2018-07-04 16:32
Any news on that one? We are also facing some issues in regards to UI Pointer hover responses for scroll views for example...

**Comment by thestonefox** [comment] 2019-04-02 07:32
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:32 UTC
Labels: unconfirmed bug, w_bug
