### ISSUE TITLE
Climbing object with a non-convex Mesh Collider - Player can fall through world geometry

### ISSUE THREAD

**Issue by sauerkraut2786** [ExtendRealityLtd/VRTK#1519] opened 2017-09-25 04:24 UTC
### Environment

 * Source of VRTK =Unity Asset Store 
 * Version of VRTK = Unity Asset Store 3.2.0
 * Version of Unity3D = 2017.1 1f1
 * Hardware used = Vive
 * SDK used = SteamVR

### Steps to reproduce

Replace the box collider from any of the off-white climbing blocks in the sample climbing scene with a non-convex Mesh Collider. When climbing that block, purposely collide the headset with the bloc - the screen initially immediately goes black (as it is supposed to) but then if you continue to push past the point where the headset is colliding with the mesh itself (ie. you have gone past the surface of the mesh) then visibility is restored and the player can see inside the object. Even worse, if the player does an unGrab (ie. stops climbing) when the headset is inside the mesh collider, then the player will fall through the world.

Scenario: I am using a voxel based engine to generate a complex mountainous landscape and the voxel engine (Voxeland) generates with a non-convex Mesh Collider. In my game I would like the player to be able to climb the voxel mesh, or at the very least climb objects (eg. rocks) that are embedded in the wall. Currently climbing itself works brilliantly apart from the player being able to easily able to fall through the world and I have no way to prevent this, therefore breaking the entire mechanic.

### Expected behavior

I know that Unity does not correctly handle TriggerStay events for Mesh Colliders (which is what the climbing script is using to determine being "inside" the collider).

1. First prize would be some way to handle Mesh Colliders in the same way as other colliders when headset enters the collider (ie. vision is black until they exit the collider. If user stops climbing inside the collider, then reset), but may not be possible.
2. Second prize - I would like a checkbox in the climbing script with an option to have the player reset to the last safe position ie. just before they collided **as soon as** the user collides with a non-concave Mesh Collider - at least this would prevent the player from falling through the world.

### Current behavior

As above - while climbing player can see inside objects with non-convex Mesh Colliders and if they release climb while headset is inside, they are not reset to the last safe position but instead fall through the geometry.

**Comment by thestonefox** [comment] 2017-09-25 11:43
You need to provide information about the mesh collider you're using.

It could be simply your mesh collider is too thin, if that's the case you'd need to fix your colliders.

**Comment by sauerkraut2786** [comment] 2017-09-25 11:48
Hi thestonefox - not sure what you mean by "too thin". The problem is (as stated above) easily reproducible in the climbing demo scene if you simply change any of the colliders in the off-white walls objects from box to non-concave mesh colliders. The wall objects are several metres thick, and the problem occurs when the headset is "just" within the wall.

**Comment by thestonefox** [comment] 2017-09-25 11:51
To change it to a mesh collider you need to provide a mesh. What mesh should I be providing?

**Comment by sauerkraut2786** [comment] 2017-09-25 11:59
If you remove the box collider and then add a mesh collider it will use the cube's mesh automatically.

**Comment by thestonefox** [comment] 2017-09-25 12:07
Are you sure what you're suggesting is something that actually works within unity? to me, using the cube primitive mesh for a mesh collider is just going to cause problems anyway.

**Comment by sauerkraut2786** [comment] 2017-09-25 12:24
I just know that the behaviour I am seeing on my voxel terrain generated mesh is identical to when I use the cube primitive in the dem scene. Ie. I am climbing and move my head forward into the block. As the headset moves into the block I first see black (as expected) then if I keep moving further in the black dissappears and I can see into the geometry. If I stop climbing at that point I fall into the geometry. This only seems to happen with a non convex mesh collider. I haven't tried this with any other imported objects with mesh colliders.

**Comment by sauerkraut2786** [comment] 2017-09-25 19:17
Did you try it?

**Comment by thestonefox** [comment] 2019-04-02 07:29
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:29 UTC
Labels: unconfirmed bug, w_bug
