### ISSUE TITLE
Bug - GearVR Controller Model

### ISSUE THREAD

**Issue by prashant-naidu** [ExtendRealityLtd/VRTK#1716] opened 2018-01-29 18:52 UTC
Environment

Source of VRTK - GitHub
Version of VRTK - 3.3.0 alpha
Version of Unity3D - 5.6.4f1
Hardware used - GearVR
SDK used - Oculus Utilities, Ovravatar

Steps to reproduce

1. Setup a basic VRTK Unity Scene with the sdk manager, controller scripts, and an sdk_setup for GearVR
2. Add the OVRCameraRig and LocalAvatar prefabs to the sdk_setup for the gearVR

Expected behavior

Spawn in the blank scene and see the tracked gearvr controller model being tracked.

Current behavior

The tracked model appears far above the camerarig and a static model of the controller appears in front of the camerarig. It looks like the tracked model is appearing at the calibration height set for the rift

Additional information

I'm assuming this is because the base controller class hasn't implemented a model rendering method case for the new gearvr models in ovravatar.

**Comment by thestonefox** [comment] 2019-04-02 07:32
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:32 UTC
Labels: unconfirmed bug, w_bug
