### ISSUE TITLE
'No Controller Model' exception using VRTK_ControllerHighlighter - reproducible in example scenes

### ISSUE THREAD

**Issue by AzzyDude24601** [ExtendRealityLtd/VRTK#1856] opened 2018-07-16 17:10 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github): **Github** 
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash): **Latest commit d88c9ea  on Jun 14**
 * Version of Unity3D (e.g. Unity 5.4.4f1): **2018.1.8f1**
 * Hardware used (e.g. Vive/Oculus): **Vive**
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities): **SteamVR**

### Steps to reproduce

1. Open any example scene from the VRTK master repository
2. Add VRTK_Controller Highlighter to either left/right ControllerScriptAlias.
3. Change the colour of an element e.g. 'Highlight Touchpad'.

### Expected behavior

Controller element changes colour without any error exception.

### Current behavior

Controller element changes colour and you recieve the error: 
"Exception: No Controller Model could be found. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown."

**Comment by thestonefox** [comment] 2019-03-30 11:18
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:18 UTC
