### ISSUE TITLE
Would interactable support multiple interactors interact with sth. at the same time and could be expended to scale, direction, scroll, highlight,rope skipping，etc.

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [ExtendRealityLtd/VRTK#2076] opened 2019-11-10 09:46 UTC
**Environment**

1.VRTK.Prefab 1.1.4
2.Unity 2019.2.1f1
3.Hardware used (Oculus Rift)
4.SDK used (Oculus Intergation)

**Current behavior**

The current primary/secondary interactable is too basic and just support one hands real move to interact.

**Expected behavior**

I expect the interaction is multiple interactors interact with sth. at the same time and could be expended to scale, direction, scroll, highlight,rope skipping, etc. Base performance is just like holding the plate or Tear a piece of cloth or Break a stick even or Take hold of the rope and jump with two hands.

**Comment by thestonefox** [comment] 2019-11-10 10:59
You're going to need to clarify this more because at the moment it makes little sense as to what the issue is

**Comment by BelieveXiaoShuai** [comment] 2019-11-10 12:24
Or may be just like holding the plate with two hands.

**Comment by thestonefox** [comment] 2019-11-10 15:48
I'm going to close this issue until it is clear what it is asking for

**Closed by thestonefox** 2019-11-10 15:48 UTC
