### ISSUE TITLE
SnapDropZone cannot reset ishover OnDisable

### ISSUE THREAD

**Issue by atmuc** [ExtendRealityLtd/VRTK#1830] opened 2018-06-11 07:35 UTC
### Environment

Github Master version (20 May 2018)
Oculus Rift

### Steps to reproduce

place an interactable object in the range of Hover. this will set interactable's Hovered Over Snap Drop Zone
Disable Snap Drop Zone

### Expected behavior

Interactable's Hovered Over Snap Drop Zone is reset

### Current behavior

Interactable's Hovered Over Snap Drop Zone is true forever.

**Comment by thestonefox** [comment] 2019-03-30 11:20
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:20 UTC
Labels: unconfirmed bug
