### ISSUE TITLE
Adding messages and intuitive component creation to the inspector

### ISSUE THREAD

**Issue by dantman** [ExtendRealityLtd/VRTK#938] opened 2017-02-18 08:20 UTC
While working on the #900 keyboard functionality I ended up implementing editor scripts to display error and info messages in the inspector when some part of configuration required attention and to easily create required components out of a selection of multiple pluggable implementations.

This won't be necessary or useful for all parts of VRTK; but if there are any other parts of VRTK that make use of interconnecting components with multiple implementations, I could probably apply this technique to make working with those parts easier without needing to know exactly what collection of components you need to add ahead of time.

One example of where this technique might be useful would be the joint system. We have a bunch of different joint implementations and you need to exit unity and read the documentation to figure out how to use them.

![vrtk-keyboard](https://cloud.githubusercontent.com/assets/53399/23091592/803bfed0-f56e-11e6-9998-a385bb971e25.gif)

**Comment by thestonefox** [comment] 2017-02-21 11:25
Yeah I quite like that idea.

**Comment by bddckr** [comment] 2017-02-21 11:30
Same here, a very good idea.

I'm not sure if I'd rather want those things as some kind of extra editor wizard that only applies the components after everything is set up.
Looks great already, anyway! :+1:

**Comment by dantman** [comment] 2017-02-21 15:35
The only idea of where else it could be used so far is the joint system. @thestonefox @bddckr Do either of you have an idea of anywhere else we have a bunch of different implementations of something that could use an easier way to create components or could use a help message?

**Comment by bddckr** [comment] 2017-02-21 17:49
I think the various `Interact*` grabs could need some kind of wizard or helpful messages. You can easily forget to add one (or don't know about them) and the interactable objects won't work correctly in all regards.

**Comment by dantman** [comment] 2017-02-23 00:12
Ok, #954 is my first addition. Smart warning messages in the interactable objects and controller actions inspectors when `VRTK_Interact{Touch,Grab,Use}` scripts are missing from a controller and an interactable object is present in the scene that requires it.

**Comment by dantman** [comment] 2017-03-07 21:24
In the YouTube livestream "Loic Argelies" had an issue with the chest script and "Craig Sanford" helped out with a response. Sounds like `VRTK_Chest` and perhaps some of the other helper scripts could be the next thing to add hints to.

**Comment by dantman** [comment] 2017-05-16 05:11
The new SDK manager could probably use this treatment as well.

For example, if we detect the SteamVR Plugin's prefab at the normal asset path the SDK Manager could have an info bubble mentioning the availability of the SteamVR SDK and have a "Setup now" button that'll automatically create the SDK Manager object, SteamVR prefabs, and autopopulate everything.

We could also have a wizard mode where in the SDK Manager inspector there's a "Setup New SDK" box with a dropdown selector for SDKs defaulting to None. When you pick a SDK the wizard will show a bit of help/documentation for the SDK pointing you to the assets you need to install (whether on the store or on something like Oculus' website) and then pointing you to return to the SDK Manager at which point that SDK Setup bubble could have the same "Setup now" button that the info bubble would have.

**Comment by thestonefox** [comment] 2019-04-02 07:39
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:39 UTC
Labels: enhancement, w_feature
