### ISSUE TITLE
RadialMenu not rendered correctly using Oculus

### ISSUE THREAD

**Issue by ewolf29** [ExtendRealityLtd/VRTK#1861] opened 2018-08-02 08:41 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK:  [d88c9ea](https://github.com/thestonefox/VRTK/commit/d88c9eafc31975bb9566e5747c12e48e5f75fa3d)
 * Version of Unity3D: V2017.4.0f1
 * Hardware used: Oculus 
* SDK used:  Oculus Utilities v1.27.0, OVRPlugin v1.27.0, SDK v1.28.0.

### Steps to reproduce

1. Create a scene and add all the stuff to use Oculus with VRTK.
2. Add GameObject for LeftController and add ControllerEvents Script
3. Add RadialMenu Prefab to LeftController
4. Change ButtonColor e.g. to red

![grafik](https://user-images.githubusercontent.com/10095919/43571960-904a71c2-963e-11e8-9789-2da5d5ac675e.png)

5. Run scene and touch the left controller thumbstick that the menu will open.
6. See that the menu is not rendered correctly.

![grafik](https://user-images.githubusercontent.com/10095919/43572171-185e75ea-963f-11e8-9073-c2411b8be2cf.png)

### Expected behavior

The icons supposed to be rendered on the buttons. Adding an 'Offset Distance' should drag the buttons further away from the centre.

### Current behavior

I got some strange behaviour with the VRTK radial menu. I don't know what's exactly the problem but when adding a radial menu to a controller the menu button icons a not rendered on the menu buttons. I assume also that some properties like 'Offset Distance' are not working correctly because changing the value does not show any effect. I tried to debug the problem but could not find any obvious error.

**Comment by thestonefox** [comment] 2019-03-30 11:18
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:18 UTC
