### ISSUE TITLE
(Interact with objects) Pointer does not register Touch events on other InteractableObjects whilst an item is grabbed 

### ISSUE THREAD

**Issue by codemonkeynorth** [ExtendRealityLtd/VRTK#1769] opened 2018-04-10 22:01 UTC
### Steps to reproduce

1) Open [005_Interactions] Interactable Objects

_(to allow you to "hover" over the objects so pointers turn green...)_

2) Set the Controller Pointers to be `Activate on Enable`, , Set the `Activation Button` to `Undefined` and enable `Interact with Objects`

3) Remove the `Policy List` from the `Teleporter` (set to None)

_(to test the pointer hover...)_

4) add an  `Interactable Object UnityEvents` script to the `CloneCylinderToSnap` object in the `SnapDropZonesStation` 

5) add an `InteractableObject Unity Event` for `On Touch` and tell it to set the `Mesh Renderer` for `CloneCylinderToSnap` to `enabled=false`, and the opposite for `On UnTouch`. (This will turn the cylinder invisible on pointer "hover")

6) run the app, you'll need to first go over to the other table with the `Interact On` lever to allow the pointer to trigger touch. then go back to the `SnapDropZonesStation` confirm `CloneCylinderToSnap` turns invisible on "hover" with the pointer

7) grab  the `Scale SaucerToSnap` item next to `CloneCylinderToSnap`, then try and "hover" over the `CloneCylinderToSnap` again with the pointer (note the pointers are green but the Touch event doesn't fire and it doesn't turn invisible)

### Expected behavior

If the pointer is green, and hits an `Interactable Object` then the target object events such as `Touch` should fire, regardless of whether the user has an item grabbed to the controller or not

### Current behavior

Touch/Untouch events etc are not fired by the pointer hitting an `Interactable Object` when the user has an object grabbed

### Environment

* Source of VRTK (Github)
* Version of VRTK (Github Current Master Version)
* Version of Unity3D (2017.3.1f1)
* Hardware used (Oculus)
* SDK used (SteamVR)

**Comment by codemonkeynorth** [comment] 2018-04-13 00:57
if you have a grabbed object overlap on the controller, the touch events don't fire ... maybe it blocks a raycast to the controller that triggers the event? 

modified the example above slightly...  i've turned off parts of `ScaleSaucerToSnap` to just leave the sphere.. then shifted the Y up a bit. at this position the touch events don't fire on the Yellow cylinder. If i move the sphere a little bit further up, then they do fire ok. So it's not an issue with the events as such, it's how they are being determined that's the problem

![pointer-touch-overlap-issue](https://user-images.githubusercontent.com/20189985/38711405-63c10aa4-3ebd-11e8-8caa-84885e74228d.jpg)

**Comment by thestonefox** [comment] 2018-04-13 10:33
The grabbed item relies on the fact that you are also touching it.

As soon as you grab something you can't touch something else.

if you want to attach something to you then use a snap drop zone to snap it to the controller rather than fake it with grabbing

**Comment by codemonkeynorth** [comment] 2018-04-13 12:06
Ah thanks I hadn’t thought of doing that. I will give that implementation a go and close this if it works as expected.

It does logically make sense that you’re only touching one thing at a time, but It’s slightly confusing because the “Interact with Objects” setting and the green pointer suggest that the interaction on the other object should work , but the concept of “Touch” vs “Hover” isn’t separated or implemented.

Maybe worth putting in a feature request for a “PointerOver” event on the InteractableObject itself that works along with the object highlight ? (Since as mentioned above the PointerOver still fires).

**Comment by thestonefox** [comment] 2019-04-02 07:31
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:31 UTC
Labels: unconfirmed bug
