### ISSUE TITLE
Default Snapped Object detected as new ObjectSnappedToDropZone on awake

### ISSUE THREAD

**Issue by RenaudAmedro** [ExtendRealityLtd/VRTK#1917] opened 2018-11-05 11:13 UTC
### Environment

 * VRTK Unity Asset Store
 * VRTK V3.2.1
 * Unity 2017.3.1f1
 * HTC VIVE
 * SteamVR

### Steps to reproduce

I create a wall with multiple Snap Drop Zone inside an empty game object as parent.
I set some objects , with custom attached script, in the Default Snapped Object case, on the editor, all differents for each Snap Drop Zone.

### Expected behavior

On awake, my script check the value of each objects snapped in the Snap Drop Zone, and subscribe to the ObjectSnappedToDropZone event for each SnapDropZone, to get if the object is unsapped or snapped. 

### Current behavior

For some reason, some of the Snap Drop Zone detect as a new snapped object the default snapped object they have.
After verification in my script i didn't find any clue that can help me to debug this.

**Comment by thestonefox** [comment] 2019-03-29 18:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:16 UTC
