### ISSUE TITLE
Oculus GO Button Two events only firing if  Back button pressed and released quickly.

### ISSUE THREAD

**Issue by hawkwood** [ExtendRealityLtd/VRTK#1908] opened 2018-10-02 01:02 UTC
### Environment

VRTK: Master on Github, commit 80db756d9f0a653236e3ff6f0ce4516ea1581111
Unity 2018.2.8 on macOS 10.13.6
Oculus GO
SDK: Oculus modified for Go/GearVR

### Steps to reproduce + Current behavior

1. Build and run VRTK/Examples/"[001 - Interactions] ControllerEvents" (modified for GO/GearVR) on Oculus GO
2. Press and hold trigger (then release) to verify actions are logging.
3. Click (press and release) the controller's "<-" (Back) button, see both pressed then released events for "Button Two" logged.
4. Press and hold "<-" button, then release after a few seconds, see no events logged.

### Expected behavior

On step 4, I would expect the "pressed" event to be logged when the button is pressed, then the "released" event to be logged when it was released.  I also made an "Escape Key" tester, and it logged events properly.

**Comment by thanathozz** [comment] 2018-10-10 06:00
Hello hawkwood - i experienced the exact same issue. I personally believe this has nothing to do with VRTK, but with the oculus go controller itself / gearVR. Have you found a solution? I feel like gearvr wont detect wether the button is held down or not..

**Comment by hawkwood** [comment] 2018-10-10 15:46
I made a test package to see if the native input was registering the DOWN and UP separately, and it was, so this is an issue with VRTK.  I was able to set this aside for the time being so I have not worked on solving it.

**Comment by shaneharris** [comment] 2019-03-28 14:01
This might be a bit late but just to comment on this - https://developer.oculus.com/documentation/unity/latest/concepts/unity-ovrinput/

`
The ‘Back’ button on Oculus Go only supports the functionality of GetUp() as the ‘Back’ button only reports a change in status during the frame that the button is released. This button does not report a change in status when pressed.
`

Based on the above its working as intended - therefore this issue should probably be closed.

**Comment by thestonefox** [comment] 2019-03-29 18:17
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:17 UTC
