### ISSUE TITLE
Controllers not interacting with the UI in WindowsMR UWP Build ( Works fine in the editor playmode)

### ISSUE THREAD

**Issue by albinhw** [ExtendRealityLtd/VRTK#1885] opened 2018-08-30 04:19 UTC
### Environment

 * Source : Github
 * Version of VRTK : 3.3.0
 * Version of Unity3D : 2017.4.8, 2017.4.10
 * Hardware used : WindowsMR Device
 * SDK used : UWP,

### Steps to reproduce
1. Add a world space canvas with VRTK_UICanvas Attached to it.
2. Add some UI elements to the canvas
3. Check if the UI is interactive with the controller in editor ( It works without any issues in editor)
4. Build a UWP app and try interacting with the UI using the controller ( The UI is not interacting in the build)

### Expected behavior
The controller should interact with the UI elements in the canvas as it does in the editor playmode

### Current behavior

In the UWP build the the canvas elements are not interacting with the controller. It works fine in the editor.

**Comment by albinhw** [comment] 2018-08-30 07:07
@bddckr @thestonefox Please let me know if there is any workaround to fix this immediately, I am about to complete a project which has lot of UI interactions. Unfortunately I hadn't tried building the project before. Thanks!

**Comment by bddckr** [comment] 2018-08-30 11:41
Your best bet to get help is the VRTK [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general.

**Comment by beccannlittle** [comment] 2018-09-11 16:33
I am having this issue as well. [Here](https://github.com/Innoactive/VRTK-Windows-MR-Extension/issues/8) is a possible workaround, haven't tried it yet.

**Comment by bddckr** [comment] 2018-09-14 16:39
@beccannlittle @rockwalrus Thanks for figuring this out!

Unity states one can put the link file in the Assets folder directly `or any subdirectory of Assets`, so I believe we should be able to ship it with VRTK, though I wonder what happens if you have multiple link files.

Is anyone of you able to check whether multiple link files in a project work?

Thanks again!

**Comment by beccannlittle** [comment] 2018-09-14 17:41
@bddckr from that Unity Manual page:

> A project can include multiple link.xml files. Each link.xml file can specify a number of different options.

**Comment by albinhw** [comment] 2018-09-15 06:01
@beccannlittle : Thanks for sharing. It was really helpful. You are a life saver!

**Comment by bddckr** [comment] 2018-09-15 08:09
Damn I totally didn't see that. I need a vacation 😅

Thanks for sharing, will try to get that in soon.

**Comment by thestonefox** [comment] 2019-03-30 11:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:16 UTC
