### ISSUE TITLE
InteractableObject components are too configuration heavy to be at the root of every grabbable prefab

### ISSUE THREAD

**Issue by dantman** [ExtendRealityLtd/VRTK#1553] opened 2017-10-10 10:17 UTC
## Problem
The per-object config space for interactable object system is problematically large.

An interactable object **must** be configured with 2-4+ VRTK components 1+ of them with a large amount of configuration properties in the inspector (from what I see, typically totalling up to 2 scroll pages in the inspector of interaction components and their properties). And because of the way it works this all **must** be at the root of the prefab with the object's most crucial components.

I have a game with hundreds of prefabs for small grabbable objects (various cans, random types of "trash", medical "tools", mugs, snacks, etc...). All of these are types of objects you'd be able to grab so they have to be setup as interactable objects. They have various materials, meshes, colliders, impact sounds, configuration for their "debris" properties, and rigidbody weights/drag and can be dropped separately into map scenes so it's justified for them to be individual prefabs. However 99% of these follow one of the same 4 patterns for their VRTK configuration.

This is problematic because:
* Every one of these 100s of prefabs need to have 2 pages of VRTK components in them
* These components need to be at the root of the prefab
* The same configuration of these pile of component properties is duplicated between dozens of prefabs, if I need to update a single property or swap a component (eg: tweak haptic strength or switch between child/joint grab attach in my game) I need to update hundreds of prefabs

None of the standard ways of fixing this type of issue work:
* The components must be on the root so I can't move them to a child component to organize my prefabs (like how you'd push meshes, colliders, triggers, and audio sources in children)
* Unity still doesn't support nested/extending prefabs, so I can't make a base prefab for small grabbable objects and make my cans, mugs, snacks, etc... extend it
* The interactable configuration is made up of a complex set of several Unity components, so I can't just extend something and create a single pre-configured component to use in my prefabs
* There are dozens of properties across several that need configuring, so I can't just dynamically create the components at runtime without a pile of code
* Instantiate can only be used to create a whole game object, not merge it with another so I can't put interactable components in one prefab and at runtime Instantiate/merge that with my objects
* In Unity it's not a normal practice to copy or work with serialized components and create them at runtime, that's an Editor/internal pattern, so I can't make a prefab with the interactable components and copy them to my objects at runtime

## The solution?
I think the simplest fix to this problem would probably be to make the root/rigidbody target configurable (like how components that use VRTK_ControllerEvents or a peer VRTK_Interact* component have an optional `controller` or `controllerEvents` property to make the link) and this can be updated at runtime.

Then I would be able to make 2-4 prefab "templates" with VRTK interactable components for the various patterns of interactable object I have. On my own "debris" script assign one of these prefabs as the interaction template to use for that prefab. And at runtime I can `Instantiate` the prefab as a child and assign the rigidbody/root of the component.

### Notes
* `VRTK_InteractableObject` already has a protected `interactableRigidbody`. If this is required than it could be made public and treated as the root for the interactable object; otherwise we'll have to create a new property.
* `VRTK_InteractableObject` will need to update a few direct references to `gameObject` and `transform` to use the root/interactableRigidbody property.
* `VRTK_InteractTouch.GetColliderInteractableObject` will need some way other than `collider.GetComponentInParent<VRTK_InteractableObject>()` to find the interactable object
* We may need something similar to `VRTK_PlayerObject` to decouple it from the root. Given that, properties like `interactableRigidbody`, and other references rather than making the root a public property it may be better as a protected serializable field (so it can be assigned in the editor but not assigned at runtime) and some sort of `SetInteractableRoot` method can be used for runtime assignment.
* For the most parts scripts outside of the scripts belonging to the InteractableObject get a `VRTK_InteractableObject` and don't try messing with its children assuming the interactable object is at the root. Aside from `VRTK_InteractTouch` which does `collider.transform.IsChildOf(touchedObject.transform)` and checks for a `VRTK_InteractableObject` in the parent of the `collider.gameObject` in `IsObjectInteractable`.

**Comment by thestonefox** [comment] 2017-10-10 10:23
Raise a PR with the proposed solution, it's hard to understand what the problem and solution actually are from this issue text.

**Comment by dantman** [comment] 2017-10-10 10:54
@thestonefox Ok, a few bikeshed questions so I can match VRTK's paint first.

* I'll probably need to create a runtime-only component like `VRTK_PlayerObject` to denote the root of an `InteractableObject` and link to the `VRTK_InteractableObject` component it belongs to. What should I name it?
* Should I make `VRTK_InteractableObject` require a `Rigidbody` to work, or create a separate GameObject property for the root?
* What term would you like to call the root of an InteractableObject by? "root", "interactableRoot", or...

**Comment by thestonefox** [comment] 2017-10-10 10:56
An interactable object doesn't require a rigidbody to work, for instance the climbable interactable objects don't need a rigidbody. Also the new grab mechanics of transform move and rotate move don't need rigidbodies (and they can also work just on trigger colliders).

as far as naming, i dunno, come up with something (even a placeholder for now) and that can be discussed along with the PR.

**Comment by dantman** [comment] 2017-10-16 12:48
@thestonefox Why does `VRTK_InteractTouch` use `GameObject`s for `touchedObject`, `colliderInteractableObject`, and `StopTouching`? Wouldn't it have made more sense for it to be the `VRTK_InteractableObject`? It seems to be expected of it and it's the only component used on that object (aside from looking for colliders in the children).

**Comment by thestonefox** [comment] 2017-10-16 12:49
@dantman yeah Grab and Use do the same i think, i have a post-it note with replacing it (and deprecating it properly). I'll get round to it :p

**Comment by dantman** [comment] 2017-10-16 22:03
@thestonefox How big a breaking change is it / when can you include it?

My changes make the code related to those 3 properties/methods a bit more messy with an extra layer of component checks to go through. The code would flatten down nicely if I did that refactor now at the same time as making the change.

**Comment by thestonefox** [comment] 2017-10-16 22:08
It will affect many parts of the code as they rely on GameObjects being passed about. So things need deprecating and pragma blocks to remove the deprecation warnings.

**Comment by thestonefox** [comment] 2019-04-02 07:37
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:37 UTC
