### ISSUE TITLE
WindowsMR ControllerColliders use fallback

### ISSUE THREAD

**Issue by beccannlittle** [ExtendRealityLtd/VRTK#1878] opened 2018-08-21 23:21 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK:: 3.3.0 (d88c9ea)
 * Version of Unity3D: 2018.1.0f2
 * Hardware used: Samsung Odyssey
 * SDK used: WindowsMR

### Steps to reproduce

- Follow instructions for enabling native WMR SDK (NOT SteamVR)
- Follow instructions for using VRTK-Windows-MR-Extension 
- Enter Play mode and inspect `[VRTK][AUTOGEN][Controller][CollidersContainer]` which can be found under the SDK Setups as a child of the script alias

Also, see [SDK_WindowsMRController.cs](https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Source/SDK/WindowsMR/SDK_WindowsMRController.cs) on [line 208](https://github.com/thestonefox/VRTK/blob/7cda0b8a326b8d9ba04e9191cd4c5d70c2de4744/Assets/VRTK/Source/SDK/WindowsMR/SDK_WindowsMRController.cs#L208):
```
public override string GetControllerDefaultColliderPath(ControllerHand hand)
{
    //TODO: Implement
    return "ControllerColliders/Fallback";
}
```

### Expected behavior

We should see colliders relevant to the WMR controllers.

### Current behavior

We see the fallback collider, which is a simple sphere.

### Workaround

I copied `SteamVRWindowsMRController_Left` and `SteamVRWindowsMRController_Right` from `VRTK > Source > SDK > SteamVR > Resources > ControllerColliders` and pasted them into a new `ControllerColliders` folder under `WindowsMR > Resources`. I modified them a little to make them fit better to the model, but its not perfect. 

I also modified `GetControllerDefaultColliderPath` in `SDK_WindowsMRController.cs`:
```
public override string GetControllerDefaultColliderPath(ControllerHand hand)
{
    return (hand == ControllerHand.Left ? "ControllerColliders/SteamVRWindowsMRController_Left" : "ControllerColliders/SteamVRWindowsMRController_Right");
}
```

**Comment by thestonefox** [comment] 2019-03-30 11:17
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:17 UTC
