### ISSUE TITLE
React to Teleportation with Destination Marker Events 

### ISSUE THREAD

**Issue by IARI** [ExtendRealityLtd/VRTK#1692] opened 2018-01-09 15:25 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.3.0 alpha (6cb308689b6d786ad62f28bb7e34ca8dec1f6018 on 3.3.0 alpha branch)
 * Version of Unity3D: Unity 2017.3.0f3
 * Hardware used: Vive
 * SteamVR

### Steps to reproduce

1. Open 044_CameraRig
2. Create a simple script for the purpose of logging events:
```
public class TestLogger : MonoBehaviour
{
        public void Log(String message)
        {
                Debug.Log(message);
        }
}
```
3. Add a `TestLogger ` component to any gameobject in the scene.
4. Add the `VRTK_DestinationMarker_UnityEvents
` to a DestinationPoint in the scene,
and Log all events with some sample test string, i.e. as in the following image

![vrtk_destinationmarker_unityevents](https://user-images.githubusercontent.com/1053417/34727982-dc9a6f32-f558-11e7-939c-ae19e5345c9d.png)

### Expected behavior

All events but the `DestinationMarkerSet` seem to fire as expected (even though imo the documentation could use clarification)

When the user teleports to the DestinationPoint, I had expected the `DestinationMarkerSet` to fire, although from the documentation it doesn't seem entirely clear to me:

> DestinationMarkerSet - Emitted when the destination marker is active in the scene to determine the last destination position (useful for selecting and teleporting).

In 3.2.1, this was the case (the event fired on teleportation as i xpected.)

### Current behavior

in 3.3.0 the `DestinationMarkerSet` does not fire anymore.

**Comment by IARI** [comment] 2018-01-09 16:10
I believe 5f4e36007bfe2837969037776d976ada61c03990 might be to blame.
checking that out ...

**Comment by LangTao92** [comment] 2018-06-25 11:36
Yes, I developed this in 2018.1.0 with 3.3.0, the DestinationMarkerSet is error found the bug, I can't resolve this problem that I set a custom event by DestinationMarkerSet

**Comment by thestonefox** [comment] 2019-04-02 07:34
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:34 UTC
Labels: unconfirmed bug, w_bug
