### ISSUE TITLE
Intergrate Mozilla Web VR

### ISSUE THREAD

**Issue by mitchelldmccollum** [ExtendRealityLtd/VRTK#1910] opened 2018-10-09 16:20 UTC
Feature Request
Im not sure if someone suggested this but im working with Mozillas WebVR tools for Unity and it would make life really easy if I could use the VRTK tool kit with it. As it stands all you can do is look around in there toolkit so having VRTK integration would make development easy and could help push VR to the masses. 

https://github.com/mozilla/unity-webvr-export

**Comment by thestonefox** [comment] 2019-03-29 18:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:16 UTC
