### ISSUE TITLE
VRTK_BasePointerRenderer.Toggle() not working

### ISSUE THREAD

**Issue by prashant-naidu** [ExtendRealityLtd/VRTK#1719] opened 2018-01-30 22:05 UTC
Environment
------------------

Source of VRTK - GitHub
Version of VRTK - 3.3.0 alpha
Version of Unity3D - 5.6.4f1
Hardware used - Oculus Rift
SDK used - Oculus Utilities, Ovravatar

Steps to reproduce
--------------------------

1. Create basic VRTK Scene and add a StraightPointerRenderer and all required associated scripts (ControllerEvents, Pointer, UI_Pointer) to the inspector
2. Create a script where you are toggling the renderer's visibilty using VRTK_BasePointerRenderer.Toggle()

Expected behavior
--------------------------

StraightPointerRenderer toggles on/off approriately

Current behavior
----------------------

StraightPointerRenderer stays on/off

Additional information
-----------------------------

Maybe this is because I don't have some public vars on the scripts setup properly for this method to work?

**Comment by prashant-naidu** [comment] 2018-01-30 22:07
1. ...to a controller gameObject*

**Comment by prashant-naidu** [comment] 2018-01-30 23:33
currently getting around this by doing this:

```RightControllerReference.GetComponent<VRTK_StraightPointerRenderer>().tracerVisibility = VRTK_BasePointerRenderer.VisibilityStates.AlwaysOff;```

**Comment by prashant-naidu** [comment] 2018-01-30 23:33
not that great :L

**Comment by bddckr** [comment] 2018-01-31 07:17
You need to recreate it *in an example scene*. There's too many steps to produce "a basic VRTK Scene" that can be done wrong.

There are several scenes using pointers.

**Comment by thestonefox** [comment] 2019-04-02 07:32
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:32 UTC
Labels: unconfirmed bug, w_bug
