### ISSUE TITLE
feat: Separate GearVR SDK_Setup from OculusVR SDK_Setup

### ISSUE THREAD

**Issue by prashant-naidu** [ExtendRealityLtd/VRTK#1717] opened 2018-01-29 21:07 UTC
At the moment, to build for gearvr I have to change the quick select in a single sdk_setup script since both the gear and rift use the same sdk. This can be difficult when I want each platform to have different gameobject in their hierarchy (ie. different controller models, etc)

**Comment by prashant-naidu** [comment] 2018-01-29 21:10
Also building for both require switching the quick select between platforms, when the implied behavior is to have them both show up in the priority stack in sdk_manager

**Comment by thestonefox** [comment] 2019-04-02 07:32
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:32 UTC
