### ISSUE TITLE
Unable to rename game object in hierarchy when using SnapDropZones Unity 2018.x

### ISSUE THREAD

**Issue by bhermer** [ExtendRealityLtd/VRTK#1880] opened 2018-08-22 08:15 UTC
The Problem

When in VRTK_Snap Drop Zone script, having the Highlight Object Prefab populated, it causes Unity to be unable to rename objects in the hierarchy.

Replicate:
Windows 10
New Unity project (version 2018.x, not tested with 2017)
Add VRTK (latest as of today 22/08/18)
Add SteamVR
open [005 - interactions] example
try to rename with F2 or slow double click, you cant.
Find  the ScalingSnapPoint > SnapDropZone
remove ScaleSaucerToSnap from VRTK_SnapDropZone
You can now rename.

**Comment by NatMonney** [comment] 2018-11-22 12:30
I can confirm the Issue. To be able to rename any object in my scene, the solution was to disable the VRTK_SnapDropZone script.

**Comment by thestonefox** [comment] 2019-03-30 11:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:16 UTC
