### ISSUE TITLE
Cannot fire pistol in VRTK4 Farm example with Simulator

### ISSUE THREAD

**Issue by hyperh** [ExtendRealityLtd/VRTK#2014] opened 2019-05-17 04:39 UTC
### Environment

* Source of VRTK: GitHub
* Version of VRTK: VRTK4, master ec844cb9d4e0ad9e8193bbeb25e2bbba0215caba
* Version of the Unity software: Unity 2019.1.0f2
* Hardware used: n/a
* SDK used: OpenVR/SteamVR

### Steps to reproduce

1. Open VRTK4 > Samples > Farm > Scene
1. Run scene
1. Select simulator

### Expected behavior

After picking up the pistol, pressing the right mouse button should fire it.

### Current behavior

Does not fire when right mouse button is pressed.

Side note would be that a tutorial on how to do use actions on interactables would be helpful. There's one already on how to grab, but nothing on how to use, so I can't really tell what's wrong or how to make my own.

Great work on this project! Thanks for your dedication!

**Comment by thestonefox** [comment] 2019-05-17 05:57
Technically not a bug, more of a shortcoming in the example scene.

The gun is fired by a float action reaching its max value of `1f` the simulator `Use` button is just a boolean action so it doesn't emit any float data for the gun to fire with.

It's an easy enough fix though, the Simulator `Use` button which is a `BooleanAction` can be converted into a float (off = 0f | on = 1f) which can then be passed into the gun.

I'll update the example scene with this so at least the Simulator works as expected.

**Comment by thestonefox** [comment] 2019-05-24 09:00
This has been fixed now in the latest GitHub master

**Closed by thestonefox** 2019-05-24 09:00 UTC
Labels: bug
