### ISSUE TITLE
Body Physics broken on Sloped Terrains

### ISSUE THREAD

**Issue by clamchoda** [ExtendRealityLtd/VRTK#1094] opened 2017-04-04 17:22 UTC
**Environment**
**Source of VRTK**: Asset Store and GitHub
**Version of VRTK**: 3.1.0
**Version of Unity3D**: Unity 5.5.0f3
**Hardware used**: Vive
**SDK used**: SteamVR

I know we know about the Body Physics sliding down hills, but this introduces a new issue on sloped terrains. Since the RigidBody turns to isKinematic when falling, it also allows us to slide through all the walls, buildings, obstacles ect on the way down the hill.

**Steps to reproduce**
You can repo this by opening  example scene 17 and adding a terrain hill with a wall on the side. See pic below. Wiggle around and try to fall down the slope into the wall. A lot of the times it will stop you, but it is easy to get through with a little bit of wiggling (activating the fall mechanism to turn the rigid body to isKenematic)

http://tinypic.com/r/2iv1hcz/9

I think position rewind would solve this, but also sometimes position rewind puts you on the other side of the wall. So it will sometimes have the same results. 

**Expected behavior
Briefly describe what you expect should happen** : Character should stop at wall
**Current behavior
Briefly describe what is actually happening**: Character goes through wall

Video: https://youtu.be/PEQnWgSfeuQ

**Comment by thestonefox** [comment] 2017-04-14 15:14
Did you try the updateed version of the body physics to see if this still happens?

**Comment by clamchoda** [comment] 2017-04-14 16:50
I'm quite new here around git hub, but I tried pull request that you created for body physics last week, but it did not resolve the issue. If there is a more recently modified version I will give that a try

**Comment by thestonefox** [comment] 2017-04-14 17:44
Just give the latest version of github master a go, see if it works. If not then lets keep looking at it

**Comment by clamchoda** [comment] 2017-04-15 17:30
Hello @thestonefox . Gave the master a go, but the problem still exists.

Thank you

**Comment by thestonefox** [comment] 2019-04-02 07:28
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:28 UTC
Labels: unconfirmed bug, w_bug
