### ISSUE TITLE
Locomotion studder

### ISSUE THREAD

**Issue by zealousappex** [ExtendRealityLtd/VRTK#1780] opened 2018-05-01 05:04 UTC
1. Running Github VRTK.
2. Open: "[006 - Locomotion] MovementTypes"
3. Set the "locomotionType" to walk in the direct your controller is facing, using the touchpad to walk.
4. Walk around any object looking at it, while walking around it you can see it stutter.

I changed the "physics timestep" but that didn't help.

I was reading this and this seems to be the issue: http://www.kinematicsoup.com/news/2016/8/9/rrypp5tkubynjwxhxjzd42s3o034o8

-VRTK Github
-Unity 2017.3.1f1
-Vive
-SteamVR

**Comment by amarillo-sebas** [comment] 2018-05-02 02:26
Same problem for 042_CameraRig_MoveInPlace.

**Comment by JWNJWN** [comment] 2018-05-18 04:47
Changing your fixed TimeStep to 1/90 should stop this stuttering. 
Can you try this and respond back?

**Comment by zealousappex** [comment] 2018-06-15 14:18
This is still an issue and I believe it is to do with VRTJ using update rather then fixed update. Like I mentioned I already have changed my physics timestep.

**Comment by JWNJWN** [comment] 2018-06-15 15:56
This only occurs if your physics timestep differs from your regular timestep. This will be the case if you haven't set your physics timestep to the correct value, (1/90) for desktop vr, or if frame drops are occuring.
Unless one of those is true I cannot reproduce this bug.

**Comment by zealousappex** [comment] 2018-06-15 17:02
If you have a minute to conferm, are you setting your "LeftController" to "Device For Direction" to "**left Controller**" when testing?
I made a video of the studder: https://www.youtube.com/watch?reload=9&v=tfVHt8WBJSg
I am running a:
GTX 1080TI
I7-8700K @4.0 16GB ram

**Comment by JWNJWN** [comment] 2018-06-15 17:10
Ok, I must've missed that setting last time XD
I'll change it so they update on fixed update and pr it :)

**Comment by zealousappex** [comment] 2018-06-15 17:15
Thank you so much!

**Comment by thestonefox** [comment] 2019-04-02 07:30
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:30 UTC
Labels: unconfirmed bug, waiting for update
