### ISSUE TITLE
Inconsistent behavior when using teleport pointer "Select on Deactivate"

### ISSUE THREAD

**Issue by afonseca08** [ExtendRealityLtd/VRTK#2027] opened 2019-06-05 20:50 UTC
### Environment

* Source of VRTK (Unity Asset Store or GitHub).
Github

* Version of VRTK (Unity Asset Store/GitHub release number) (GitHub master commit hash).
aa7644cf

* Version of the Unity software (e.g. Unity 2018.3).
2019.1.0f2

* Hardware used (e.g. Vive/Oculus).
Oculus Rift

* SDK used (e.g. OpenVR/SteamVR/Oculus Utilities).
OpenVR

### Steps to reproduce

1. Open Farm ExampleScene.
2. Configure the right teleport pointer, RightCurvedPointer as follows:
Selection Action: ActivatePointer (BooleanAction)
Selection Method: Select on Deactivate
3. Run the sample scene and test teleport with Simulated Camera Rig.
4. Run the sample scene and test teleport with Oculus VR right controller.
5. Compare results.

### Expected behavior
Behavior is the same in steps 3 and 4. The user is able to teleport by selecting and releasing the teleport control.

### Current behavior

Step 3: Clicking the middle mouse button brings up the teleport control, releasing it teleports to the indicated location as expected.

Step 4: Touching the thumbstick on the Oculus controller brings up the teleport control, releasing it does not teleport.

Additional notes:
Discussed with @thestonefox in Slack and it appears to be a race condition. Verified by modifying the ObjectPointer.Internal Actions Activate and SelectOnRelease as follows:
Disabled Activate GameObject
Added to SelectOnRelease a Behaviour Enabled Observer, to observe the SelectOnRelease and enable the Activate GameObject.

With this workaround the behavior was consistent on my machine.

**Comment by lachlansleight** [comment] 2019-06-06 03:20
Just wanted to add a data-point to this: I have SelectOnRelease working perfectly on the Rift S using the Oculus SDK. However on the Quest I have the same problem as OP - the pointer appears but the teleportation doesn't happen.

Some debug logging revealed that the TransformData being passed to the Teleport function is null, seemingly caused by `bool IsActivated` on the ObjectPointer being false when its Select method is called.
(as well as `activePointsCastData.IsValid` being false and `HoverTarget` being null).

I can confirm that the workaround solves the problem on my machine. Thanks heaps for including it in your Issue @afonseca08 !

**Comment by thestonefox** [comment] 2019-06-06 07:32
Actually I think this can be fixed by just fixing the prefabs so the workaround is always in place.. I'll take a look

**Comment by thestonefox** [comment] 2019-06-07 07:50
@afonseca08 I still can't recreate the issue locally (the joy of race conditions)

But can you try this PR for me https://github.com/ExtendRealityLtd/VRTK/pull/2029

and see if it fixes the issue for you. I'm hoping this will ensure the order is always the same and would be a nicer solution than having to update the prefab.

**Comment by afonseca08** [comment] 2019-06-09 05:25
@thestonefox Yes, I just tried it and it fixes the issue. I confirmed it works consistently using the Simulated Camera Rig as well as the Oculus touch controllers in the sample scene. Also confirmed in my own test scene as well.

**Closed** 2019-06-09 08:53 UTC
Labels: bug
