### ISSUE TITLE
Pointer Interaction with Interactable Objects

### ISSUE THREAD

**Issue by UnityBob** [ExtendRealityLtd/VRTK#1925] opened 2018-11-29 12:09 UTC
### Environment

 * Source of VRTK -> VRTK Master from Github
 * Version of VRTK -> Master
 * Version of Unity3D -> 2018.2.14f1
 * Hardware used -> Oculus Go/VRTK Simulator in Unity
 * SDK used -> VRSimulator

### Steps to reproduce

- Open VRTK example Scene [005 - Interactions] InteractableObjects
- Move to PointerInteractionStation
- Add VRTK_InteractObjectHighlighter script to all "whirlygigs"
- Delete the Handlebars on the station and toggle Pointer>Interact with objects and Pointer>Grab to Pointer Tip to enabled

### Expected behavior

Being able to interact with the "whirlygigs" by pointing the pointer at them.
- Pointing on them with activated Pointer should activate TouchHighlight
- Pressing the Grab Button should grab the objects at tip of the pointer
- Pressing the Use Button should make them spin

### Current behavior

None of the expected behaviors will occur.
Usage only possible if Use Settings > Pointer Activates Use Action is activated on the Object and the Pointer Selection Button is pressed (NOT the Use OverrideButton!)

**Comment by thestonefox** [comment] 2018-11-29 14:12
I can't reproduce this. Maybe it's an issue with Oculus Go, but works fine on the Oculus Rift

**Comment by UnityBob** [comment] 2018-11-29 14:15
Maybe try testing it with using the VRSimulator. Unfortunately im not able to test with Rift in Unity.

**Comment by UnityBob** [comment] 2018-11-29 16:32
![screen1](https://user-images.githubusercontent.com/45456640/49236338-3289cd00-f3fc-11e8-8183-8c2caca813ae.png)
- Controller(green) outside of InteractableObject
![screen2](https://user-images.githubusercontent.com/45456640/49236339-3289cd00-f3fc-11e8-849e-82b6de49f491.png)
- Controller inside of Object
- TochHighlightColor = yellow
![screen3](https://user-images.githubusercontent.com/45456640/49236340-3289cd00-f3fc-11e8-9b03-996ba448bbb6.png)
- Pointer on Object
- no TouchHighlightColor
![screen4](https://user-images.githubusercontent.com/45456640/49236341-3289cd00-f3fc-11e8-8ad3-cab48ee6e556.png)
- Object Script
![screen5](https://user-images.githubusercontent.com/45456640/49236344-3289cd00-f3fc-11e8-965f-704d6040992e.png)
- ControllerAlias

**Comment by thestonefox** [comment] 2019-03-29 18:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:16 UTC
