### ISSUE TITLE
VRTK_Pointer/Interact With Objects, Renderer Visible On Grab

### ISSUE THREAD

**Issue by PixelRacoon** [ExtendRealityLtd/VRTK#1767] opened 2018-04-10 20:21 UTC
Iam realy new to this, so i´m sorry for not doing it right. :)

First of, **StoneFox** you did an amazing job with this and you and all the other people are pushing the boundaries of VR Coding with unity, thank you all for that.

So maybe this is a small thing but i dont have a sollution yet.

### Steps to reproduce
* Open Scene 5 Object Interaction
* Activate  **"Interact With Objects"** in the **"VRTK_Pointer (Script)"** on your controller.
* Put **"VRTK_Interact Object Appearance"**  on the desired object and deactivate **"Renderer Visible On Grab"**
* Grab the given object with the Pointer of the teleporter.

The Controller will be still visible and doesnt dissappear as it should cause it has grabbed the object.

### Expected behavior
If you use the Grab teleport the controller should dissapear.

### Current behavior
The Controller stays Visible if you grab through the teleport pointer.

 * Source of VRTK (Github)
 * Version of VRTK (Github Current Master Version)
 * Version of Unity3D (2017.3.1f1)
 * Hardware used (Oculus)
 * SDK used (SteamVR)

Best regards

**Comment by PixelRacoon** [comment] 2018-04-13 15:06
Yes, thats the exact problem.
Iam using SteamVR with my Oculus Headset and Conrollers.

So i tryed it multiple times on one object, with different Distances and angles and sometimes it works and sometimes it doesnt.

**Comment by thestonefox** [comment] 2019-04-02 07:32
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:32 UTC
Labels: unconfirmed bug
