### ISSUE TITLE
IPointerClickHandler is not proccessed correctly.

### ISSUE THREAD

**Issue by Supert** [ExtendRealityLtd/VRTK#1841] opened 2018-06-25 16:59 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK: master/d88c9eafc31975bb9566e5747c12e48e5f75fa3d
 * Version of Unity3D: 2017.3.0f3
 * Hardware used: none
 * SDK used: Simulator

### Steps to reproduce

1. Set up canvas and pointer as documentation suggests.
2 Add Image with MonoBehaviour script implementing IPointerClickHandler.
3. Add Image with MonoBehaviour script implementing IPointerDownHandler.
4. Add Button.
5. Run and try to click everything.

### Expected behavior

IPointerClickHandler.OnPointerClick, IPointerDownHandler, and Button.onClick are called.

### Current behavior

IPointerClickHandler.OnPointerClick is not called.

### Suggestions

VRTK_VRInputModule does not process clicks correctly. Take a look how it is done in [TouchInputManager](https://github.com/tenpn/unity3d-ui/blob/1f5289211cc97e3feb63d5f847141258127386ff/UnityEngine.UI/EventSystem/InputModules/TouchInputModule.cs)

**Comment by thestonefox** [comment] 2019-03-30 11:20
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:20 UTC
Labels: unconfirmed bug
