### ISSUE TITLE
When using AxisMovement, the joysticks will fail or lose control.

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [ExtendRealityLtd/VRTK#2097] opened 2020-02-26 14:26 UTC
### Environment

* Code source: Unity Packages
* Code version: VRTK Prefabs 1.1.9/Tilia Input UnityInputManager 1.2.3
* Platform version: Unity 2019.2.1f1
* 3rd party dependencies: None
* Hardware Used: Oculus Rift/Quest

### Steps to reproduce

1. Start play mode and go open options-menu -> slide locomotion options to "axis movement".
2. Climb up the Windmill.
3. Climb high and fall down, and shake the joystick at the same time.
4. AxisMovement would lose effect and Freeze in place or lose control to keep moveing.

### Expected behavior

That axis movement should work normally without losing effect or losing control.

### Current behavior

from the air to the ground, the axismovement would lose effect.

**Comment by thestonefox** [comment] 2020-02-26 14:28
duplicate of https://github.com/ExtendRealityLtd/VRTK/issues/2093

**Closed by thestonefox** 2020-02-26 14:28 UTC
