### ISSUE TITLE
Hierarchical InteractableObjects lose highlights on reenable (OutlineCopyObjectHighlighter)

### ISSUE THREAD

**Issue by Flavelius** [ExtendRealityLtd/VRTK#1703] opened 2018-01-17 19:07 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github)
AssetStore
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.2.1
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.3.0p1
 * Hardware used (e.g. Vive/Oculus)
Oculus Rift
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
Oculus Rift AssetStore SDK package

### Steps to reproduce
Multiple InteractableObjects hierarchically put inside each other with OutlineCopyObjectHighlighter lose their highlight objects after disabling the hierarchy.

### Expected behavior

highlighting should still work after renabling the hierarchy

### Current behavior

The DeleteExistingHighlightModels() function removes _all_ child highlights.
With these statements, only finding the immediate children, it works correctly:
`
foreach (Transform t in transform)
{
    var h = t.GetComponent<VRTK_PlayerObject>();
    if (h != null && h.objectType == VRTK_PlayerObject.ObjectTypes.Highlighter) Destroy(h.gameObject);
}
`

**Comment by thestonefox** [comment] 2019-04-02 07:32
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:32 UTC
Labels: unconfirmed bug, w_bug
