### ISSUE TITLE
Simulator breaks if scene is reloaded

### ISSUE THREAD

**Issue by rockwalrus** [ExtendRealityLtd/VRTK#1929] opened 2018-12-27 20:11 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.3.0
 * Version of Unity3D: 2018.2.6f1
 * Hardware used: WMR
 * SDK used: Simulator

### Steps to reproduce

Create two scenes. One should have the standard VRTK setup, including the `VRSimulator` SDK. The other should have a GameObject that additively loads the first scene, unloads it, then additively loads it again.

### Expected behavior

The simulator should work as expected. 

### Current behavior

Myriad `NullReferenceExceptions`. A bit of detective work traces the source of the issue to SDK_InputSimulator.FindInScene(). The static `destroyed` field is set to `true` early in the Simulator's loading sequence, which leads to `null`s getting cached.

**Comment by thestonefox** [comment] 2019-03-29 18:15
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:15 UTC
