### ISSUE TITLE
Oculus Go positions head/hands under floor

### ISSUE THREAD

**Issue by Scraft** [ExtendRealityLtd/VRTK#1960] opened 2019-03-27 17:00 UTC
### Environment

Source of VRTK: Github, Master
Version of VRTK: bf584452ff8df5f5fd71ae148b642131b5820fb7
Version of Unity3D: 2018.2.21f1
Hardware used: Oculus Go
SDK used: Oculus Utilities

### Steps to reproduce

Open an example scene, setup SDK Manager with SDK_OCULUS_AVATAR ticked, Oculus in Auto load list, the Oculus node object references set. SDK Selection Quick Select set to 'GearVR (Android:Oculus)'. OVRCameraRig set to Floor Level. OVR Manager Target Devices set to Gear Vr or Go. Essentially just set up as per the instructions. The issue persists regardless of value of SDK_OCULUS_AVATAR .

### Expected behavior

The controller should appear where the player's hand is (roughly) and avatar head should either not appear or should follow the players head (but not obscure the player's view).

### Current behavior

The Oculus Avatar Head is rendered in the ground and the controller underground. If the origin is set to 'Eye' instead of 'Floor' the head and controller render at the correct place, however, the player is now on the floor. I feel like I am missing something, but I have spent several hours trying to resolve this with different combinations unsuccessfully.

**Comment by thestonefox** [comment] 2019-03-29 18:12
Closing this as it's releated to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:12 UTC
