### ISSUE TITLE
Teleporting fails in editor batchmode

### ISSUE THREAD

**Issue by rockwalrus** [ExtendRealityLtd/VRTK#1931] opened 2018-12-28 16:47 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.3.0
 * Version of Unity3D:2018.2.6f1
 * Hardware used: WMR
 * SDK used: WMR

### Steps to reproduce

Create a test that involves teleporting. Run it from the command line.

### Expected behavior

Teleporting should happen.

### Current behavior

Teleporting doesn't happen because the teleport code uses `WaitForEndOfFrame`, which doesn't work in batchmode on the Editor platform for [dubious reasons](https://docs.unity3d.com/Manual/CLIBatchmodeCoroutines.html).

**Comment by thestonefox** [comment] 2019-03-29 18:15
Closing this as it's releated to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:15 UTC
