### ISSUE TITLE
GearVR test project with GearVR Simulator and some examples

### ISSUE THREAD

**Issue by gpvigano** [ExtendRealityLtd/VRTK#1621] opened 2017-11-16 16:57 UTC
In <https://github.com/gpvigano/VRTK/tree/feat/gearvr-test> you can find a demo project to test a GearVR implementation with the VRTK 3.3.0 alpha from GitHub, branch `release/3.3.0-alpha`, commit  ba1f53e (I didn't make a pull request, because this maybe should be a different project).
The `master` branch didn't work with GearVR, so I'm working on the `release/3.3.0-alpha` branch.
I used Unity 5.5.4f1, Oculus package must be added installing OculusUtilities.unitypackage.

You can find instructions in `Assets/VRTK_GearVR_Test/README.md`

Some examples from VRTK were modified to work with GearVR, included here in `VRTK_GearVR_Test\Examples`.
A custom "GearVR-friendly" simulator is included in a proper SDK, see `Source/SDK/GearVRSimulator/README.md` for details.
Everything here works with the GearVR D-Pad only, it is designed just to enable interaction without a gamepad.

I hope this could help someone to use VRTK on GearVR.
Any feedback would be appreciated.

**Comment by Juandeldesierto** [comment] 2017-11-24 19:04
Great work @gpvigano this have to be greatly appreciated, will try to setup to test.

**Comment by gpvigano** [comment] 2017-11-28 07:15
Thanks @Juandeldesierto , please let me know about your tests when you are ready.

**Comment by gpvigano** [comment] 2017-11-29 15:56
@Juandeldesierto: I created a different [repository](https://github.com/gpvigano/VRTK-GearVR-Test), based on 
VRTK 3.3.0 alpha from GitHub, branch `release/3.3.0-alpha`,
commit b263d2f8982414a77dd37656a28342763ddf2d30, with another example (UI interaction) and many bugs fixed. Once built on Android you can use the GearVR back button to jump from a scene to the next one and at the end exit.

@thestonefox: I pulled from your `release/3.3.0-alpha` branch and pushed on [this new repository](https://github.com/gpvigano/VRTK-GearVR-Test), to keep a connection with the original project, while changing project settings to build on Android. If somehow this can be a problem, please let me know and tell me what to do, thanks.

**Comment by Juandeldesierto** [comment] 2017-12-02 10:41
Examples are working fine, just the gear vr controller needs better
support, in the examples movement is done by gaze head movement instead of
controller pointer location. :(

2017-11-29 16:57 GMT+01:00 Giovanni Paolo Viganò <notifications@github.com>:

**Comment by gpvigano** [comment] 2017-12-04 11:32
Sorry, unfortunately I don't have a controller for my GearVR.
The provided examples are modified to allow simple gaze-based interaction, anyway, as far as I know, the GearVR controller can work with VRTK (see this video by @thestonefox  [<https://www.youtube.com/watch?v=ma2AetALN_k>]), I think it's mapped on touchpad.
I'm not sure about what you mean by "movements", if you mean moving objects a controller can be really useful, but if it's about camera movements it must be noticed that many people suffer motion sickness: this is the reason because, in the provided examples, I limited the navigation with the GearVR to (gaze-based) teleporting.

**Comment by Juandeldesierto** [comment] 2017-12-04 12:24
Hi Giovanni,

im sorry to hear this, you should have a controller. Anyway we can help you
get one?
as you are leading this implementation.

I will try the mapping you suggested for the use of controller for movement.

On 4 Dec 2017 12:32, "Giovanni Paolo Viganò" <notifications@github.com>
wrote:

Sorry, unfortunately I don't have a controller for my GearVR.
The provided examples are modified to allow simple gaze-based interaction,
anyway, as far as I know, the GearVR controller can work with VRTK (see
this video by @thestonefox <https://github.com/thestonefox> [
https://www.youtube.com/watch?v=ma2AetALN_k]), I think it's mapped on
touchpad.
I'm not sure about what you mean by "movements", if you mean moving objects
a controller can be really useful, but if it's about camera movements it
must be noticed that many people suffer motion sickness: this is the reason
because, in the provided examples, I limited the navigation with the GearVR
to (gaze-based) teleporting.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thestonefox/VRTK/issues/1621#issuecomment-348936304>,
or mute the thread

**Comment by gpvigano** [comment] 2017-12-05 08:59
@Juandeldesierto: I don't need and I don't want a GearVR controller and I'm not "leading" this implementation. I just shared my work to help someone, anyway you can contribute, if you want.
Do you think I should just delete that repository and close this issue? No problem for me. Sorry, I don't want to make people waste time with something that seems to be useful only for me.

@thestonefox: I created a separate project to ease testing without affecting the main VRTK project. I don't want to overload your already hard work, do you think we should close this issue (or even its related repository)? If so, I perfectly understand.

**Comment by thestonefox** [comment] 2017-12-05 12:42
@gpvigano i think it's ok to leave this open if people wanna check out what you've done. As long as they realise this is a totally separate repo and isn't representative of any work currently being carried out on VRTK.

**Comment by gpvigano** [comment] 2017-12-05 13:21
OK, I just put a statement with also your words as introduction to the repository (see [this commit](https://github.com/gpvigano/VRTK-GearVR-Test/commit/f1cfd3282464d3695734dc12778ee7a3635407f9)), thanks @thestonefox.

**Comment by thestonefox** [comment] 2019-04-02 07:36
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:36 UTC
Labels: Public Service Announcement
