### ISSUE TITLE
VRTK_SnapDropZone's CleanHighlightObject and the validComponents array

### ISSUE THREAD

**Issue by Quidam2k** [ExtendRealityLtd/VRTK#1793] opened 2018-05-15 19:10 UTC
Source of VRTK: Github
Version of VRTK: 3.2.1 dated 4/29, can't figure out where to find the hash.
Version of Unity3D: 2018.1.0f2
Hardware used: Oculus
SDK used: Oculus & Simulator

I've found it useful to leave more scripts on my highlight objects than the ones laid out on line 997:
`string[] validComponents = new string[] { "Transform", "MeshFilter", "MeshRenderer", "SkinnedMeshRenderer", "VRTK_GameObjectLinker" };
`

Since overriding the method won't allow me to do this, I've been modifying the VRTK code directly, which is generally to be discouraged.

I suggest adding an optional parameter of this array to CleanHighlightObject:

`protected virtual void CleanHighlightObject(GameObject objectToClean, string[] validComponents = null)`

and a change to the code that generates it, detecting if it was supplied as a parameter

```
if (validComponents == null)
{
     validComponents = new string[] { "Transform", "MeshFilter", "MeshRenderer", "SkinnedMeshRenderer", "VRTK_GameObjectLinker" };
}
```

as doing so will allow the method to be overridden and a different set of valid components supplied when calling the base implementation.

**Comment by thestonefox** [comment] 2019-04-02 07:30
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:30 UTC
Labels: unconfirmed bug
