### ISSUE TITLE
SDK_WindowsMRBoundaries.GetPlayArea() returns correct value only once

### ISSUE THREAD

**Issue by rockwalrus** [ExtendRealityLtd/VRTK#1859] opened 2018-08-01 19:09 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github

 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
Version 3.3.0 (hash not available)

 * Version of Unity3D (e.g. Unity 5.4.4f1)
2018.1.1f1

 * Hardware used (e.g. Vive/Oculus)
Samsung Odyssey 

 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
Windows Mixed Reality

### Steps to reproduce

Create a script that calls VRTK_DeviceFinder.PlayAreaTransform() while using the WMR SDK.

### Expected behavior

The correct play area transform should be returned every time.

### Current behavior

Every time the method is called it returns the parent object of the object called the time before.

**Comment by thestonefox** [comment] 2019-03-30 11:18
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:18 UTC
