### ISSUE TITLE
Straight Renderer stoping

### ISSUE THREAD

**Issue by AhmadSays** [ExtendRealityLtd/VRTK#1887] opened 2018-09-03 19:06 UTC
Hi. I made a pause menu in my game, used a Time.timeScale = 0f;
But, when my game is paused, my pointers of controllers is freezing. 
This problem seems easy, but i still have not found a solution. 
I tried to use values near 0, but it's not a cool idea.

I used:
Unity2018.2of1
Htc Vive hardware
SteamVR plugin
VRTK from github
VRTK version is 4.0

**Comment by ahmadsay** [comment] 2018-09-08 18:33
So, apparently, no one made a pause menu with vrtk used Time.timeScale = 0f;

**Comment by bddckr** [comment] 2018-09-11 07:41
Issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. GitHub issues are only useful for proper bug reports with steps to reproduce in an example scene **like the Issue Template requires**.

**Comment by ahmadsay** [comment] 2018-09-11 07:51
Thank. Also I tried , but their say to using another method for pause game, it’s not a timescale = 0f;

**Comment by thestonefox** [comment] 2019-03-30 11:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:16 UTC
