### ISSUE TITLE
Snap Rotate and other object control actions not working properly

### ISSUE THREAD

**Issue by waad-hashem** [ExtendRealityLtd/VRTK#1913] opened 2018-10-15 10:40 UTC
### Environment

 * Source of VRTK ( Github)
 * Version of VRTK (Github master )
 * Version of Unity3D ( Unity2018.2)
 * Hardware used (Oculus)
 * SDK used (Oculus Utilities)

### Steps to reproduce
-In a new scene I have setup the sdk 
-I added a 3d plane "floor"
-I made an emptyObject "RightController" -->then linked the object to it's corresponding place in the sdk manager 
-On RightController I added the following scripts ( VRTK_controller Events,VRTK_pointer,VRTK_Streight pointer renderer , and VRTK Touchpad controls)
-I created a child object to RightController called "rotation_control" and added the snap Rotate Object Action script to it, then dragged the RightController into the object control script and set the axis change to x.
-I made a new empty object called "PA" and added the height adjust teleport script to it.
-When I run the game everything works fine until I click on the thumbstick (left or right) no rotation occurs but the screen blinks.
In the consule I recieve this error whenever I click right or left thumbstick : 

> Exception: `PlayArea` requires the `CapsuleCollider` component to be attached to the same or child GameObject.
VRTK.VRTK_Logger.Log (VRTK.VRTK_Logger+LogLevels level, System.String message, System.Boolean forcePause) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:174)
VRTK.VRTK_Logger.Error (System.String message, System.Boolean forcePause) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:130)
VRTK.VRTK_BaseObjectControlAction.GetObjectCenter (UnityEngine.Transform checkObject) (at Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_BaseObjectControlAction.cs:146)
VRTK.VRTK_BaseObjectControlAction.RotateAroundPlayer (UnityEngine.GameObject controlledGameObject, System.Single angle) (at Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_BaseObjectControlAction.cs:100)
VRTK.VRTK_SnapRotateObjectControlAction.Process (UnityEngine.GameObject controlledGameObject, UnityEngine.Transform directionDevice, UnityEngine.Vector3 axisDirection, System.Single axis, System.Single deadzone, System.Boolean currentlyFalling, System.Boolean modifierActive) (at Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_SnapRotateObjectControlAction.cs:52)
VRTK.VRTK_BaseObjectControlAction.AxisChanged (System.Object sender, VRTK.ObjectControlEventArgs e) (at Assets/VRTK/Source/Scripts/Locomotion/ObjectControlActions/VRTK_BaseObjectControlAction.cs:95)
VRTK.VRTK_ObjectControl.OnXAxisChanged (VRTK.ObjectControlEventArgs e) (at Assets/VRTK/Source/Scripts/Locomotion/VRTK_ObjectControl.cs:111)
VRTK.VRTK_TouchpadControl.ControlFixedUpdate () (at Assets/VRTK/Source/Scripts/Locomotion/VRTK_TouchpadControl.cs:58)
VRTK.VRTK_ObjectControl.FixedUpdate () (at Assets/VRTK/Source/Scripts/Locomotion/VRTK_ObjectControl.cs:173)<

### Expected behavior

The snap rotate should work fine

### Current behavior

No rotation received just blinking

**Comment by attaway** [comment] 2019-01-03 00:58
I'm having the same problem. It's strange though because it works fine in the example scene.
I'll post back here if I get it working.

**Comment by thestonefox** [comment] 2019-03-29 18:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:16 UTC

**Comment by mPAQ** [comment] 2019-10-08 19:11
Know this is closed, but alot of people still use 3.3, and this page was all I could find on this issue, luckily I was able to resolve it in my case.
This can be fixed by pasting the following into VRTK_RotateObjectControlAction
`public VRTK_BodyPhysics bodyPhysics;

        protected override void OnEnable()
        {
            internalBodyPhysics = bodyPhysics;
            base.OnEnable();
        }`
Then link your body physics to the component. Essentially there is a function in the base controller that gets skipped over for the rotation script, but not the sliding. This might only work if your actually using body physics though.
