### ISSUE TITLE
Multiple overlapping Snap Zones parented to an Interactable drop framerate to 5

### ISSUE THREAD

**Issue by Liens1** [ExtendRealityLtd/VRTK#2004] opened 2019-05-09 10:26 UTC
### Environment

* Source of VRTK (GitHub).
* Version of VRTK (v4 Github master).
* Version of the Unity software (Unity 2019.1.1f1).
* Hardware used (Oculus).
* SDK used (UnityXR).

### Steps to reproduce

1. Bring an "Interactable.Primary_Grab.Secondary_Swap" prefab into the scene (set it's scale to 0.1,0.1,0.1). Duplicate it with Ctrl+d and move it outside of the first one.

2. Bring an "InteractableSnapZone" prefab into the scene as a child of the first "Interactable.Primary_Grab.Secondary_Swap", with a local position Y of 3. Duplicate the SnapZone 8 times for a total of 9 SnapZones, all children of the first Interactable and all 3 local units on Y.

3. Run the game, grab the second Interactable and collide it with the 9 Snap Zones while maintaining the grab.

NB: Depending on the power of your system, you may need to duplicate the Snap Zones more than 8 times, it gets exponentially worse with each one added.
Also this doesn't seem to happen if the Snap Zones aren't parented to the Interactable.

### Expected behavior

No major frame loss.

### Current behavior

Major frame loss due to "LeftInteractor" CollisionTracker.OnTriggerStay() being spammed.

**Comment by thestonefox** [comment] 2019-05-09 10:27
Are all of your snap zone activation areas (the trigger collider on the snap zone) overlapping each other?

**Comment by Liens1** [comment] 2019-05-09 10:30
Yes, they are all in the exact same position. When I line them up in a row it does not happen that I can tell

**Comment by thestonefox** [comment] 2019-05-09 10:31
why do you have 9 snap zones in the same position?

Also does this only happen when 9 are a child of an interactable or can you just have 9 overlapping zones?

**Comment by Liens1** [comment] 2019-05-09 10:36
The same position is for demonstration purposes, to demonstrate the issue as I couldn't get it to happen as severely otherwise. In my project I have some zones that are simply close together not overlapping. I scale the zones from 0 to 1, so maybe there's a point where they're all overlapping, or at least all overlapping the Interactor, not sure.

It happens with any number of SnapZone children, but the more zones added the more severe the frame drop.

**Comment by thestonefox** [comment] 2019-05-09 10:45
I think the issue is the `Interactor` is still doing a fundamental collision with the `SnapZone`

A solution could be to use a `CollisionIgnorer`

and have the `Sources` set to your `Interactor` objects and the `Targets` set to your `SnapZone` objects

The CollisionIgnorer will find all colliders in a child GameObject so you could group all the SnapZones under one GameObject and then just ignore that containing GameObject.

This will now remove the base physics collisions from occurring each frame.

**Comment by Liens1** [comment] 2019-05-09 10:57
Great, seems to have done the trick.

How would a prefab find the interactor(s) though?

**Comment by thestonefox** [comment] 2019-05-09 11:42
The CollisionIgnorer would have to sit in your scene (or instantiated at runtime) as a separate object.

Then you could add your `Interactors` to the `Sources` in edit time, then at runtime whenever you instantiate a SnapZone via code you would then have a reference to the CollisionIgnorer in that code that's doing the SnapZone instantiation, and then you'd just add the instantiated SnapZone gameobject to the `CollisionIgnorer` `Targets`

**Comment by Liens1** [comment] 2019-05-09 12:17
This also seems to be an issue in the opposite scenario: If the 9 overlapping child `SnapZone`s each have an `Interactable` snapped, there is frame drop when the `Interactor` collides (ie: during an unsnap grab attempt).
The above solution does not work for this scenario.

**Comment by thestonefox** [comment] 2019-05-09 12:21
if you put an interactor into 9 overlapping zones at the same time, then which one of the snap zones should unsnap?

**Comment by Liens1** [comment] 2019-05-09 12:26
I would say the last one that was put in, but even a random one unsnapping would be preferable to massive frame drop

**Comment by thestonefox** [comment] 2019-05-09 12:29
Try making all of your SnapZones ignore each other with another Collision Ignorer

So just add all SnapZones to the Sources and all SnapZones to the Targets, then they shouldn't collide with each other (which is what i assume the problem is here)

**Comment by Liens1** [comment] 2019-05-09 12:37
That doesn't seem to be the issue, it didn't work. It's still only when the `Interactor` collides so I'm thinking there's still something to do with `Interactor` and `SnapZone` collision still happening. (`CollisonTracker.OnTriggerStay()` spam).

**Comment by thestonefox** [comment] 2019-05-09 12:39
If you've ignored all collisions between the Interactor and the SnapZone then no OnTriggerStays will fire when the Interactor enters the snap zone.

What is more likely happening is you have an interactable that can now interact with 9 snap zones and the snap zone trigger collider is being fired on all 9 snap zones because they all are being touched at the same time by the same interactable

**Comment by thestonefox** [comment] 2019-05-09 12:42
As a test, on each `InteractableSnapZone` expand them so you see their `ActivationArea` GameObject and on the `CollisionTracker` remove the `CollisionChanged` event listener (or set the execution time from `Runtime Only` to `Off`).

This will now stop any OnTriggerStay processing (I dont __think__ the SnapZone needs to know if the collision has changed)

**Comment by thestonefox** [comment] 2019-05-09 12:44
Actually what the problem may be is the CollisionTrackers on the SnapZones are all informing all of the CollisionNotifiers on the Interactables every frame too.

**Comment by Liens1** [comment] 2019-05-09 12:49
I turned off all the collision changed events in the SnapZones but it did not make a difference, still flooding with CollisonTracker.OnTriggerStay() spam coming from the Interactor

**Comment by thestonefox** [comment] 2019-05-09 12:53
ok as a quick test try this

open the `CollisionTracker.cs` file and add a new public bool like

`public bool ignoreStay;`

then in the `OnTriggerEnter` method of that file just do like

```
protected virtual void OnTriggerEnter(Collider collider)
{
  if(ignoreStay) { return; } 
  OnCollisionStarted(eventData.Set(this, true, null, collider));
}
```

Now on each of the SnapZones on their ActivationArea, find the `CollisionTracker` and tick that newly created `ignoreStay` bool on them.

I just wanna see if that removes any propagation of the physics collision stay check.


Also, side note. how do you know the OnTriggerStay is coming from the Interactor?

**Comment by thestonefox** [comment] 2019-05-09 12:54
(I made changes to the above comment, so don't copy paste from the email notification as it will be different!)

**Comment by Liens1** [comment] 2019-05-09 13:04
Didn't make a difference.

I'm using the profiler, when I click on one of the frames where the scripts are going out of control, it's saying CollisionTracker.OnTriggerStay(), FixedUpdate.PhysicsFixedUpdate & Physics.TriggerStays are making up the bulk of the frame. When I double click one of the COllisionTracker.OnTriggerStay()s it takes me to the LeftInteractor GameObject (Collision Tracker component)

**Comment by thestonefox** [comment] 2019-05-09 13:05
Can you make a really simple example scene highlighting the problem and upload the .unitypackage and i can take a look when i get chance?

**Comment by Liens1** [comment] 2019-05-09 13:54
I figured out the second issue. Putting a `CollisionIgnorer` with `Sources` as `Interactors` and `Targets` as all the `Interactable` snapped objects, rather than the SnapZones.
It fixed the issue though it's not ideal since they can no longer be interacted with and not able to be removed from the SnapZones anymore.

**Comment by thestonefox** [comment] 2019-05-09 13:56
That's not going to help because the interactors need to interact with the interactables.

If you can make the test project (super simple) and upload it I'll take a look later on

**Comment by Liens1** [comment] 2019-05-09 14:00
I would but I haven't been able to successfully reproduce it yet, but I will if I am able to

**Comment by Liens1** [comment] 2019-05-09 15:32
Do you have any ideas why the `IgnoreInteractorCollisionTag` is ignored during this initial issue? The original solution was to use a `CollisionIgnorer` but SnapZones already have the `IgnoreInteractorCollisionTag` on them

**Comment by thestonefox** [comment] 2019-05-09 16:04
The `IgnoreInteractorCollisionTag` component doesn't ignore physics collisions between two objects, it's basically used in a rule to prevent one CollisionTracker from forwarding collision data to another CollisionNotifier.

The reason it's there now, is to tell the Interactor not to forward it's collision events to any of the SnapZones....but the underlying unity Physics collisions will still be happening.

**Comment by Liens1** [comment] 2019-05-10 04:55
I see, thanks. The solution I ended up using was to FakeParent (using a script I wrote) `SnapZones` to the `Interactable` without actually parenting them, to avoid the issue all together.

**Comment by thestonefox** [comment] 2019-05-10 18:39
Were you able to recreate the original issue in a simple project so i can look over and see if there is a clear problem and a clear bug to fix?

If not, then shall we close this ticket?

**Comment by Liens1** [comment] 2019-05-11 11:12
I think it's best to close it. I wasn't able to reproduce the second one specifically, but I have a feeling the second issue here is actually issue #2005

**Closed** 2019-05-11 15:46 UTC
