### ISSUE TITLE
Bug Fix: Saving scene breaks support of Oculus GO on macOS

### ISSUE THREAD

**Issue by hawkwood** [ExtendRealityLtd/VRTK#1894] opened 2018-09-12 20:23 UTC
### Environment

VRTK 3.3.0 from Github - Commit: 71a6369a850badddb8c96135963a82b2408a54da [71a6369a]
Unity 2018.2.5f1 on macOS 10.13.6
Oculus GO
Oculus Utilities

### Steps to reproduce

On a Windows 10 PC, I followed the instructions at https://docs.google.com/document/d/1b81J7qikvHDoDq8YNBgPbuc2vOo8jykD-mgOV8vDcRs/mobilebasic
to successfully build, install, and run VRTK sample on Oculus GO.

I copied (via repo) that project to Mac and successfully built, installed, and and ran on Oculus GO without changes.

The moment I save changes to a scene, the ProjectSettings.asset are changed to remove support for Oculus/GO by changing (1) the m_BuildTargetVRSettings for Android by disabling and removing "Oculus" from m_Devices, and (2) the scriptingDefineSymbols from:

    1: CROSS_PLATFORM_INPUT;VRTK_DEFINE_OCULUS_UTILITIES_1_12_0_OR_NEWER;VRTK_DEFINE_SDK_OCULUS;VRTK_DEFINE_SDK_OCULUS_AVATAR;VRTK_VERSION_3_3_0;VRTK_VERSION_3_3_0_OR_NEWER;VRTK_VERSION_3_1_0_OR_NEWER;VRTK_VERSION_3_2_0_OR_NEWER;VRTK_VERSION_3_2_1_OR_NEWER
    4: CROSS_PLATFORM_INPUT;MOBILE_INPUT;VRTK_VERSION_3_3_0;VRTK_VERSION_3_3_0_OR_NEWER;VRTK_VERSION_3_1_0_OR_NEWER;VRTK_VERSION_3_2_0_OR_NEWER;VRTK_VERSION_3_2_1_OR_NEWER
    7: CROSS_PLATFORM_INPUT;MOBILE_INPUT;VRTK_DEFINE_OCULUS_UTILITIES_1_12_0_OR_NEWER;VRTK_DEFINE_SDK_OCULUS;VRTK_DEFINE_SDK_OCULUS_AVATAR;VRTK_VERSION_3_3_0;VRTK_VERSION_3_3_0_OR_NEWER;VRTK_VERSION_3_1_0_OR_NEWER;VRTK_VERSION_3_2_0_OR_NEWER;VRTK_VERSION_3_2_1_OR_NEWER

to:

    1: CROSS_PLATFORM_INPUT;VRTK_VERSION_3_3_0;VRTK_VERSION_3_3_0_OR_NEWER;VRTK_VERSION_3_1_0_OR_NEWER;VRTK_VERSION_3_2_0_OR_NEWER;VRTK_VERSION_3_2_1_OR_NEWER
    4: CROSS_PLATFORM_INPUT;MOBILE_INPUT;VRTK_VERSION_3_3_0;VRTK_VERSION_3_3_0_OR_NEWER;VRTK_VERSION_3_1_0_OR_NEWER;VRTK_VERSION_3_2_0_OR_NEWER;VRTK_VERSION_3_2_1_OR_NEWER
    7: CROSS_PLATFORM_INPUT;MOBILE_INPUT;VRTK_VERSION_3_3_0;VRTK_VERSION_3_3_0_OR_NEWER;VRTK_VERSION_3_1_0_OR_NEWER;VRTK_VERSION_3_2_0_OR_NEWER;VRTK_VERSION_3_2_1_OR_NEWER

The associated message in Unity are:

Scripting Define Symbols removed from [Project Settings->Player] for Standalone: VRTK_DEFINE_OCULUS_UTILITIES_1_12_0_OR_NEWER, VRTK_DEFINE_SDK_OCULUS, VRTK_DEFINE_SDK_OCULUS_AVATAR
UnityEngine.Debug:Log(Object)
VRTK.VRTK_Logger:Log(LogLevels, String, Boolean) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:160)
VRTK.VRTK_Logger:Info(String) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:120)
VRTK.VRTK_SDKManager:ManageScriptingDefineSymbols(Boolean, Boolean) (at Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs:496)
VRTK.VRTK_SDKManager:AutoManageScriptingDefineSymbolsAndManageVRSettings() (at Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs:1143)

Scripting Define Symbols removed from [Project Settings->Player] for Android: VRTK_DEFINE_OCULUS_UTILITIES_1_12_0_OR_NEWER, VRTK_DEFINE_SDK_OCULUS, VRTK_DEFINE_SDK_OCULUS_AVATAR
UnityEngine.Debug:Log(Object)
VRTK.VRTK_Logger:Log(LogLevels, String, Boolean) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:160)
VRTK.VRTK_Logger:Info(String) (at Assets/VRTK/Source/Scripts/Internal/VRTK_Logger.cs:120)
VRTK.VRTK_SDKManager:ManageScriptingDefineSymbols(Boolean, Boolean) (at Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs:496)
VRTK.VRTK_SDKManager:AutoManageScriptingDefineSymbolsAndManageVRSettings() (at Assets/VRTK/Source/Scripts/Utilities/SDK/VRTK_SDKManager.cs:1143)

Additionally [See attached images], VRTK_SDKManager SDK_OCULUS_AVATAR is not installed for Android and Standalone, and if I uncheck either, they both uncheck.  Similarly, VRTK_SDKSetup for OculusVR (renamed OculusGO) says the "GearVR (Android: Oculus)" SDK is not installed.  

### Expected behavior

I would expect VRTK to see that GearVR/OculusGO is a valid option for macOS and not disable it.

### Current behavior 
As described above.  My workaround is to make any changes I need, then reset ProjectSettings.asset so it still has to appropriate settings to build.

**Comment by thestonefox** [comment] 2019-03-30 11:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:16 UTC
