### ISSUE TITLE
No hands and start on floor with Oculus and latest versions

### ISSUE THREAD

**Issue by treendy** [ExtendRealityLtd/VRTK#1870] opened 2018-08-10 14:34 UTC
### Environment
Latest VRTK main branch
Unity version 2018.2.2f1
Oculus
SDKs (ovr_unity_utilities_Main, ovr_avatar_sdk_1.27.0 and OVRPlatformSDK_v1.24.0)

### Steps to reproduce

1. download latest VRTK github
2. open unity and open this project
3. import the latest three Oculus packages (ovr_unity_utilities_Main, ovr_avatar_sdk_1.27.0 and OVRPlatformSDK_v1.24.0)
4. open the example scene "006 Locomotion" (all scences have this issue anyway)
5. run.... player is floor level (screen is black because your head is on the floor)

_Note: I found that against the "OVRCameraRig" the script files are missing for "OVR Camera Rig (Script)" and "OVR Manager (Script)"

so i add these back in (by adding component)
I then change "Tracking Origin Type" to be Floor Level

Now i am above the floor, however i have no hands_

### Expected behavior

Would expect with latest versions that the example scenes would work with players above ground and controls/hands showing

### Current behavior

Player head is on floor, hands are not showing or working...  menioned above how i fixed the hands issue... not sure why the scripts where gone from the scene when you first open it... so guess they need to be added back in... but having know luck with the hands not working

**Comment by treendy** [comment] 2018-08-10 14:55
Infact... looking at most of the objects, im seeing a lot of "the associated script can not be loaded" in the component sections

**Comment by treendy** [comment] 2018-08-12 07:37
I think this may be why:
https://gamedev.stackexchange.com/questions/153463/the-associated-script-cannot-be-loaded-how-can-i-see-what-script-is-associate

Since this new VRTK version, we have a lot of these missing associated script components, and according to the article above, it may be due to the meta data when pulling/pushing from different developers.

so may be because this versions meta data is now not matching correctly : (

**Comment by treendy** [comment] 2018-08-12 08:16
as a work around, 
If you go to Assets/VRTK/Examples/ExampleResources/SharedResources/Prefabs/SDKManager then drag the VRTK_SDKManager prefab in to the work space, all the scripts are attached correctly.. so just delete the SDKManager that is already in the scene and reset any parameters or variable changes you made to the original one to this new one

**Comment by treendy** [comment] 2018-08-12 14:30
Im not sure i understand your answer?

If you download the latest VRTK master branch, and import only the required SDKs for Oculus to run, you will find a lot of missing scripts in the components for Oculus when you open the example scenes (see this screenshot: https://i.stack.imgur.com/ELUpf.png)

which cant be ignored, because the examples will not run.

But if you drag in the prefab used for your examples... all the scipts show correctly.

So sounds like the UID for these scripts have changed which is why the examples have lost reference to them

**Comment by bddckr** [comment] 2018-08-13 10:36
I find it very unlikely that Oculus changed the file IDs because that would mean anyone updating their package would run into trouble.

It's more likely that you're looking at additional Oculus **Avatar** package components which you didn't import into your project at the time of the screenshot?

**Comment by treendy** [comment] 2018-08-13 10:51
No, the issue isnt with Oculus, its with the master VRTK version... simply start a new project, import only your required SDKs, open an example... it wont work as expected.

To fix... i dont need to import anything else, i just delete the VRTK_SDKManager from the scene then drag another in, then just re-bind the left and right controllers... so the problem has gone for me, just anyone else who wants to try the VRTK demo running Oculus will hit this same issue

The following is a screenshot of a couple of the missing scripts within the VRTK prefab that is loaded into the scene initially

![bandicam 2018-08-13 11-45-41-416](https://user-images.githubusercontent.com/33226495/44027626-1a60e702-9eef-11e8-942d-f94cf6d2d75b.jpg)

**Comment by bddckr** [comment] 2018-08-13 11:09
Yeah something wrong there, dunno what. You can literally just revert the prefab and it will fix itself so I guess there's some version incompatibility between Unity versions that result in not matching component IDs but prefab keeps working.

**Comment by simonpaulkeating** [comment] 2018-08-13 15:36
Same issues here but I cant see a SharedResources Folder or find a [VRTK_SDKManager] anywhere in my project. I just imported the latest assets folder from GitHub.. (?)

**Comment by treendy** [comment] 2018-08-13 15:39
Should be in "Assets/VRTK/Examples/ExampleResources/SharedResources/"

**Comment by simonpaulkeating** [comment] 2018-08-13 15:44
However, when I delete old [VRTK_SDKManager] and add a new [VRTK_SDKManager] prefab I still have missing scripts and no hands. Seemingly no change at all. :(

**Comment by treendy** [comment] 2018-08-13 15:47
are you using Oculus, and do you have all the required SDK packages imported?

**Comment by simonpaulkeating** [comment] 2018-08-13 15:50
Using Occulus yes, I got the latest Occulus Utilities from their site this morning (https://developer.oculus.com/downloads/package/oculus-utilities-for-unity-5/) . Maybe its the wrong version?

**Comment by bddckr** [comment] 2018-08-13 15:52
Issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. GitHub issues are only useful for proper bug reports with steps to reproduce in an example scene like the Issue Template requires.

**Comment by Biliogadafr** [comment] 2018-08-19 15:01
I also encountered the same problem. The fix for me was to delete OVRCameraRig and LocalAvatar and add them again from Oculus SDK. For OVRCameraRig it is also necessary to set Tracking Origin Type to floor in OVR Manager. Then populate again object references for Oculus VRTK_SDK_setup and select SDK_OCULUS_AVATAR in VRTK_SDKManager (or arms will not be teleported with player).
  If I just revert LocalAvatar then some materials are not assigned and nothing works, so I need to delete and add it.
My unity version is 2018.2.2f1 and Oculus Utilities+Avatar version is 1.28  (without platform sdk).
After that I was able to check some demos, but still I was not able to bring up menu in Locomotion demo (with SteamVR it works, with Oculus SDK I had problems).

**Comment by lordvard** [comment] 2018-08-23 10:06
Thanks for your solution Biliogadafr, I managed to get it working too by first dropping a VRTK_SDKManager in a clean scene, then adding the Oculus SDK LocalAvatar Prefab into the scene. Suddenly all the missing connections on the VRTK_SDKManager solved themselves. Also noted that VRTK_SDKManager is missing references to DefaultBodyMaterialManager and DefaultHandMaterialManager which are GameObjects located under the LocalAvatar prefab. Guess this should be added to the Prefab in the VRTK Master?

**Comment by GFLMercury** [comment] 2018-09-23 10:39
Ok, this fixed the first half of the problem for me! I'm no longer a head stuck in the floor with no hands!

However, I still don't seem to have any control over the scene. No teleport, no pointer etc, just the default oculus touch controller model with absolutely no response from using any button or pad.

Any ideas?

**Comment by ethanfischer** [comment] 2019-03-20 02:58
@Biliogadafr  's steps got my hands showing up and head in the right place. But I don't have any control, teleport, or pointers either. I tried setting the Left Controller and Right Controller Script Aliases on VRTK_SDK_Manager to the LocalAvatar's controller_left and hand_left objects and also the LeftControllerScriptAlias object in the example scene, all to no avail.

**Comment by thestonefox** [comment] 2019-03-30 11:17
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:17 UTC

**Comment by NickVanHolsbeeck** [comment] 2019-05-29 11:54
@thestonefox v4 is still in beta, no? Is this issue fixed, still experiencing it in v3.3 (which is still the official lastest release)

**Comment by thestonefox** [comment] 2019-05-29 11:58
We're not working on v3.3 only v4

**Comment by dmi3ich** [comment] 2019-06-27 19:40
Hello, there. If you want to try 3.3 version, do this steps:

1. Setup VRTK plugin from unity asset store: https://www.assetstore.unity3d.com/en/#!/content/64131
2. Install Oculus Integration plugin: 1.38 (current version on the 27.06.2019): https://assetstore.unity.com/packages/tools/integration/oculus-integration-82022
3. Open demo scene and setup in [VRTK_SDKManager] -> [VRTK_SDKSetups] -> Oculus -> OVRCameraRig in OVR Manager script in Tracking - Tracking original type - Floor level.

It should works properly. 
![floor_level001](https://user-images.githubusercontent.com/7266616/60295522-347d2580-9924-11e9-993b-ac94aec784c9.PNG)
