### ISSUE TITLE
Teleport pointer is green but doesn't allow teleportation when holding an object with a custom layer

### ISSUE THREAD

**Issue by FadiBotoros** [ExtendRealityLtd/VRTK#2067] opened 2019-10-14 13:35 UTC
### Environment

* Source of VRTK: Github
* Version of VRTK: 29d098c (29d098ce511e9c18a189327b74029b193d6011a9)
* Version of the Unity software: Unity 2019.1.14f
* Hardware used: Vive
* SDK used: OpenVR

### Steps to reproduce

1. Open Example Scene
2. Change layer of the tool you will be grabbing to a custom layer.
3. Set the custom layer as a (Layer to Ignore) in the CustomRayCaster gameObject referenced in the Parabolic Line Cast script inside the ParabolicCaster gameObject  
4. Grab the tool from the hangar / garage
5. Try to teleport with the same hand while still holding the tool/object.
6. See the Teleport pointer land on the ground and turn green allowing me to teleport.
7. Click on touchpad to teleport.

### Expected behavior

I should be able to teleport while holding the object as the pointer is turning green.

### Current behavior

I can't teleport while holding a object in the same hand.

**Comment by thestonefox** [comment] 2019-10-14 13:56
Ok so not technically a code bug, more of a configuration issue in the example scene.

The problem is this:

There is is a PointersOccluded concept that says if the headset cannot see the interactors then disable the teleporter. So if you stick your hand through a wall then the teleporter will stop working as the headset doesn't have line of sight on the controller anymore.

This is causing the issue as when you pick something up, that thing is blocking the view of the controller in line of sight of the headset.

The solution here is to update the `VRTK Prefabs -> AvatarPointers -> PointerActions -> Left/RightPointerOccluded -> ObscuranceQuery` component to have a custom PhysicsCast that ignores the extra layer that the interactables are on (in the farm this is `Water`) don't ignore the `Ignore Raycast` layer in the custom physics cast otherwise it won't see the controllers either.

![image](https://user-images.githubusercontent.com/1029673/66756849-bde44380-ee92-11e9-887d-3434c799900f.png)

**Comment by FadiBotoros** [comment] 2019-10-14 15:09
Thanks! It works now after changing those settings.

**Comment by thestonefox** [comment] 2019-10-15 16:31
This is fixed now the example scene is actually a unity project and we can use custom layers

**Closed by thestonefox** 2019-10-15 16:31 UTC
Labels: bug
