### ISSUE TITLE
Black screen on HoloLens build

### ISSUE THREAD

**Issue by y3lousso** [ExtendRealityLtd/VRTK#1869] opened 2018-08-10 12:17 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github)
GitHub

 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0 ([d88c9ea](https://github.com/thestonefox/VRTK/commit/d88c9eafc31975bb9566e5747c12e48e5f75fa3d))

 * Version of Unity3D (e.g. Unity 5.4.4f1)
2018.1.4f1

 * Hardware used (e.g. Vive/Oculus)
Vive, HoloLens, Lenovo Explorer, Android

 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR, Mixed Reality Toolkit (MRTK), UnityXR

### Steps to reproduce

1 - Take any example scene you want
2 - Player settings -> use Universal Windows Platform
3 - Insert HoloToolkit and SteamVR in your Assets folder
4 - Build and run on your HoloLens

### Expected behavior

Your application should be displayed correctly on the HoloLens.

### Current behavior

You get a black screen after the splash screen on the HoloLens. It happens only on the build version, if you run your application using Holographic Remote, everything is fine.

### Quick fix

Remove SteamVR from your Assets folder when you build for UWP.

**Comment by bddckr** [comment] 2018-08-11 13:57
PRs welcome. I don't think anyone ever helping us with VRTK has a HoloLens.

**Comment by lordvard** [comment] 2018-09-18 21:00
I'm actually having the same issue but with a WMR headset, so I although Hololens probably isn't directly supported by VRTK, it seems this affects the WMR headsets too. Works fine in the Editor, but builds are unable to load VRTK. 

Here's the error when running the solution in VS as I mentioned in Slack: 
"Exception thrown at 0x00007FFC6179A388 in Woeful Woebots.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000007C11EFD720. The script behaviour 'VRTK.VRTK_SDKManager' could not be instantiated!"
and
"A script behaviour (probably VRTK.VRTK_SDKManager?) has a different serialization layout when loading. (Read 32 bytes but expected 92 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?"

**Comment by thestonefox** [comment] 2019-03-30 11:17
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:17 UTC
