### ISSUE TITLE
How to get controller Reference for object attached to controller

### ISSUE THREAD

**Issue by TheBricktop** [ExtendRealityLtd/VRTK#1935] opened 2019-01-30 16:03 UTC
Im trying to use the method that takes sdkbaseController.controllerhand left or right enums but it doesnt do anything, reference is still null. 
Is there any reasonable way to automatically get the reference for haptic rumble?

**Comment by thestonefox** [comment] 2019-03-29 18:15
Closing this as it's releated to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:15 UTC
