### ISSUE TITLE
VRTK_PhysicsSlider sets up the join in the wrong position when local coordinates are different scale from world coordinates

### ISSUE THREAD

**Issue by Baxter900** [ExtendRealityLtd/VRTK#1842] opened 2018-06-26 04:10 UTC
### Environment

 This occurs as of VRTK commit d88c9ea on Unity 2018.1.0f2 with the Oculus Rift (Oculus Utilities), should be independent of Unity Version and VR SDK/Hardware.

### Steps to reproduce

Create an empty and scale it to a non-1 size (<0.2, 0.2, 0.2> for example) then place a PhysicsSlider as its child and place a visual marker (also as a child) in the same place as the slider's default position so you can see where it moves. Length doesn't matter much, just needs to not be super short. Hit play and notice that the slider is no longer in that position, move the slider position to 0.5 and notice that it's still not in that position.

### Expected behavior
Slider should be in the position it's in on the editor once the game is running. The position it's in should also either match up to the gizmo gui making it the edge of the slider, or should be centered and the gizmo gui modified.

### Fix
In VRTK_PhysicsSlider.cs:385, replace the existing line ```transform.localPosition = originalLocalPosition + (AxisDirection() * (maximumLength * 0.5f));``` with the line ```transform.localPosition = originalLocalPosition + transform.InverseTransformVector(AxisDirection(true) * (maximumLength * 0.5f));```

### Fix Explanation
When the joint for the physics slider is created, it always assumes that where the transform is when the joint is created is the center. That shouldn't be the case for consistency with the ArtificialSlider, so it appears an attempt was made to move the object by half the total distance immediately before initializing the joint. If this had worked properly, it would make it so that the original position of the slider would be an edge of the slider.

However, that modification is incorrect currently. it modifies the originalLocalPosition by half of maximumLength in the axis declared (AxisDirection() with no parameters in this case gives the axis in the local coordinate system). However, maximumLength is a length in the world coordinate system. This results in maximumLength being too small if the sliders local coordinate system is smaller than the world coordinates, or too large if the opposite's true. The fix to this is to instead get the axis in world coordinatees (AxisDirection(true) does this) then multiply maximum length by it (since maximum length is correct while working in world coordinates. Finally, convert the world coordinates to local coordinates using InverseTransformVector.

**Comment by thestonefox** [comment] 2019-03-30 11:20
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:20 UTC
Labels: unconfirmed bug
