### ISSUE TITLE
pusher object not applying operate axis to rigidbody constraints

### ISSUE THREAD

**Issue by ezavesky** [ExtendRealityLtd/VRTK#1851] opened 2018-07-10 13:36 UTC
### Environment
Using github version of VRTK (3.2.1) and Unity 2017.3.0f3 in simulator.

### Steps to reproduce
Using either physics scripts (e.g. VRTK_Physics Pusher), the created rigid body (if one is auto created by an empty `Connected To` setting) does not apply position restrictions for other axes.  

### Current behavior
For example, if restricted to `Y Axis` for the *OperatingAxis*, the button can still be moved in X or Z, which appears to violate spatial constraints.

### Expected behavior
One would expect the auto-created rigid body to apply constraints in the other directions so that the button can move in only one direction.  This can be easily accomplished by simply bounding the rigid body with a few additional lines, like so (possibly near [this line of code](https://github.com/thestonefox/VRTK/blob/81a9c215d8af42277ee508de90b63ad1d2ddd788/Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsPusher.cs#L152)).

```
        Rigidbody rb = GetComponent<Rigidbody>();
        if (rb)     // forcibly update the rigid body
        {
            rb.constraints = RigidbodyConstraints.FreezeRotation | RigidbodyConstraints.FreezePositionX | RigidbodyConstraints.FreezePositionZ;
        }
```

### Bonus Points
Not the core of this issue, but it would be great if there was a way to restrict button pressing in the opposite direction of the `Pressed Distance` function.  Specifically, prevent people from pushing a Y-locked button **UP** and out of its spatial area.  This may (not tested right now) be accomplished by removing the absolute function from [this line of code](https://github.com/thestonefox/VRTK/blob/81a9c215d8af42277ee508de90b63ad1d2ddd788/Assets/VRTK/Source/Scripts/Interactions/Interactables/Controllables/Physics/VRTK_PhysicsPusher.cs#L274).

**Comment by ezavesky** [comment] 2018-07-14 13:52
Update here, which will require issue text refinement; the trouble came from an off-axis button.  Namely one that was placed on a console at 25 deg rotation instead of just flat. That way the forces from the user were off axis, which may have negative effects on the movement sensor.  Will try to experiment with fixes as well.

**Comment by thestonefox** [comment] 2019-03-30 11:19
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:19 UTC
