### ISSUE TITLE
Grab action doesn´t work in built solution but it works inside Unity

### ISSUE THREAD

**Issue by AngelSimOwl** [ExtendRealityLtd/VRTK#1854] opened 2018-07-13 14:42 UTC
### Environment

 * VRTK 3.2
 * Unity 2017.3.3f1
 * OVR Avatar 1.26 and Utilities 1.26
 * Oculus Rift
 * Oculus Utilities

### Steps to reproduce

Load OVR Avatar, Oculus Utility and VRTK inside the project. 

  > Do not upload custom projects with custom code to demonstrate the issue.

### Expected behavior
Grabbing objects correctly.

### Current behavior

My own scenes and the vrtk examples works fine in Unity. I mean, I can grab objects correctly in Unity editor. The problem, when I built the solution (.exe) and run the application I can not interact with grabbable objects. Furthermore the solution does not show the hands.

**Comment by bddckr** [comment] 2018-07-13 17:56
VRTK 3.2.X is over a year old. Use the GitHub master instead.

Issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here.

**Comment by thestonefox** [comment] 2019-03-30 11:18
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:18 UTC
