### ISSUE TITLE
Programmatically select with Pointer and UIPointer 

### ISSUE THREAD

**Issue by rockwalrus** [ExtendRealityLtd/VRTK#1957] opened 2019-03-20 23:11 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github): Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash): 3.3.0
 * Version of Unity3D (e.g. Unity 5.4.4f1): 2018.2.6f1
 * Hardware used (e.g. Vive/Oculus): HP
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities): WMR

### Desired behavior

Just like we have `Pointer.Toggle()` to activate and deactivate the pointer manually, it would be nice to be able to  call a method on the pointer to perform a select. We need this because our control scheme for teleporting is more complicated than a simple button press. A public method that calls `ExecuteSelectionButtonAction()` is sufficient to implement this.

There's no `UIPointer.Toggle()`, but it's easy enough to work around that by setting `activationMode` to `AlwaysOn`. On the other hand, there is no easy workaround for a lack of `UIPointer.Select()`. We ended up copying and pasting some calls to `ExecuteEvents.ExecuteHeirarchy` from `VRInputModule` using data from `UIPointer.hoveringElement`, but being able to call a method on `UIPointer` would be much less hacky.

**Comment by thestonefox** [comment] 2019-03-29 18:14
Closing this as it's releated to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:14 UTC
