### ISSUE TITLE
VRTK_OutlineObjectCopyHighlighter not working in Android platform

### ISSUE THREAD

**Issue by gpvigano** [ExtendRealityLtd/VRTK#1620] opened 2017-11-16 10:16 UTC
### Environment

VRTK 3.3.0 alpha from GitHub, branch release/3.3.0-alpha, commit  ba1f53e
Unity 5.5.4f1, Unity 2017.2.0f3
GearVR/Oculus

### Steps to reproduce

Switch to Android Platform, configure Player Settings/Other Settings for GearVR (
  Color Space = Gamma, 
  GPU Skinning = false
  Virtual Reality Supported = true
  Virtual Reality SDKs = Oculus
  Stereo Rendering Method = Multi Pass
  Minimum API Level = API Level 22).
Load example `005_Controller_BasicObjectGrabbing`, highlight the `Sphere_HightlightOnTouch` object.

### Expected behavior

An outline of the `Sphere_HightlightOnTouch` object should be rendered.

### Current behavior

A black sphere is rendered instead, Z-fighting with the original sphere.

**Comment by gpvigano** [comment] 2017-11-16 10:20
I hope I am wrong and there is a configuration to make it work, otherwise I understand this is not a critical issue, but I think at least a warning message should be printed, maybe to inform the developer that this is not his/her fault...

**Comment by gpvigano** [comment] 2017-12-01 11:02
Now the problem seems to be fixed in Android build (probably because I just updated my device), but it is still present in Unity Editor (Game window). This suggests that this behavior probably is not caused by VRTK itself, maybe it's just a matter of shader compilation or graphic drivers.

**Comment by thestonefox** [comment] 2019-04-02 07:37
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:37 UTC
Labels: unconfirmed bug, w_bug
