### ISSUE TITLE
Mixed Input For Mixed Reality

### ISSUE THREAD

**Issue by jbat100** [ExtendRealityLtd/VRTK#1626] opened 2017-11-20 09:54 UTC
This issue aims to clarify the position of VRTK contributors when it comes to mixed reality and user input, in particular with respect to Windows Mixed Reality (WMR, there is an issue for an SDK implementation [here ](https://github.com/thestonefox/VRTK/issues/1565)) but also in general. The arrival of WMR has blurred lines between VRTK’s turf (pure VR controller based platforms such as Occulus/VIVE), gaze and gesture based interfaces (Hololens), and immersive extensions to desktops where world space 2D interfaces and traditional input methods (keyboard, mouse, touch, pads) are used heavily along with 3D content. 

Currently, VRTK's controller input metaphor is strongly tied to motion controllers with grip, trigger, touchpad controls available on VIVE/Rift/WMR. In the context of the wider 4.0 input system discussion,  there is a strong case to be made that VRTK would gain from supporting a wider array of inputs for some of its functionality. For example when trying to use VRTK_UIPointer (and the very handy VRTK internal custom event system, input module and raycaster) to interact with UI elements using gaze and mouse in WMR, we ended up modifying VRTK_UIPointer replacing the tightly coupled VRTK_Controller with a more generic controller which allowed the VRTK_UIPointer to be used with gaze, gestures, mouse, or motion controllers interchangeably. Other areas which could benefit from diversified input sources could include locomotion and teleportation.

As a startup with both strong links to Microsoft/WMR and a good appreciation of the power of VRTK both as a framework and a community driven development effort, we are ready to invest a significant amount of effort working on VRTK SDKs for the various WMR headsets (Acer, Lenovo, Dell...) and would like to get a feel for how strongly the community feels whether for or against the idea of diversified, mixed inputs, and whether VRTK aims to keep its focus on 'pure' VR or is open to extending its scope to XR, any comments are welcome.

**Comment by thestonefox** [comment] 2017-11-20 09:56
The chances of VRTK supporting anything beyond 3.3.0 is extremely unlikely in the event of no serious financial investment.

**Comment by bddckr** [comment] 2017-11-20 12:41
Note #1594 and #1523.

**Comment by jbat100** [comment] 2017-11-21 10:37
Just realised the pain you were going through for WMR on the slack channel. If anyone's interested in mixed input UIPointers let us know.

**Comment by thestonefox** [comment] 2019-04-02 07:36
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:36 UTC
Labels: enhancement
