### ISSUE TITLE
SnapDropZone does not fire Pointer events like Touch (does not act as InteractableObject)

### ISSUE THREAD

**Issue by codemonkeynorth** [ExtendRealityLtd/VRTK#1768] opened 2018-04-10 21:51 UTC
### Steps to reproduce

1) Open [005_Interactions] Interactable Objects

_(to allow you to "hover" over the objects so pointers turn green...)_

2) Set the Controller Pointers to be `Activate on Enable` and, Set the `Activation Button` to `Undefined` 
3) Remove the Policy List from the Teleporter

_(to test the pointer hover...)_

4) add an Interactable Object and Interactable Objects UnityEvents script to the `SnapDropZone` object in the `SnapDropZonesStation` _(possibly VRTK SnapDropZone conflicts with VRTK Interactable Object though)_

5) add an `InteractableObject Unity Event` for `On Touch` and tell it to set `CloneCylinderToSnap` to `active=false`, and the opposite for `On UnTouch`

### Expected behavior

`SnapDropZone` should ideally respond to pointer events either when an `Interactable Object` script is added, or it should behave like an `Interactable Object` by default

in this demo...
The `CloneCylinderToSnap` should hide when the pointer hits the `SnapDropZone` and turns green. It should then show again when the pointer leaves the `SnapDropZone`

### Current behavior

Touch/Untouch events etc are not fired by the pointer hitting the SphereCollider on the SnapDropZone

### Environment

* Source of VRTK (Github)
* Version of VRTK (Github Current Master Version)
* Version of Unity3D (2017.3.1f1)
* Hardware used (Oculus)
* SDK used (SteamVR)

**Comment by codemonkeynorth** [comment] 2018-04-10 22:38
note if you add the `VRTK_Controller Pointer Events_Listener Example` script to the `LeftController` or `RightController`, you can see the hover is working fine (and hence the pointer is turning green).. it's just that the `SnapDropZone` won't react to this

`Controller on index '0' is POINTER HOVER at a distance of 4.860892 on object named [SnapDropZone] on the collider named [SnapDropZone] - the pointer tip position is/was: (30.7, 1.4, -19.0)
UnityEngine.Debug:Log(Object)`

**Comment by thestonefox** [comment] 2018-04-13 10:24
I don't understand what you're trying to do?

A snap drop zone isn't an interactable object, they are different things, you shouldn't be putting interactable object scripts on the snap drop zone object.

If you want a snap drop zone attached to an interactable object then you should child accordingly.

**Comment by codemonkeynorth** [comment] 2018-04-13 13:04
@thestonefox  I wanted to be able to have a SnapDropZone that I can `ForceSnap` an object to when I click on it with the pointer (from a distance). But it doesn't receive `Touch`  events

If I child it in an `InteractableObject` then I believe the parent's Collider interferes with the SnapDropZone collider. 

I guess I could dynamically turn that parent Collider off though on click before calling the `ForceSnap` . Will try that thanks

**Comment by thestonefox** [comment] 2018-04-13 17:47
This doesn't seem like a bug but more of a case where it doesn't fit the use case you're trying to use.

**Comment by codemonkeynorth** [comment] 2018-04-13 22:15
thanks. I guess that's true. I just assumed any interactable object with a collider would return a `Touch` event, but it's not actually an `InteractableObject` and can't have the script added to it.

**Comment by kristianpd** [comment] 2018-04-19 19:11
Should we close this issue?

**Comment by codemonkeynorth** [comment] 2018-04-19 22:10
well it does leave the problem that you can't get a `Touch` event from an SDZ when interacting with the pointers. You may for instance want to point to it, click on it and have something snap to it. As well as being able to use it normally.

But assuming any trigger collider for the touch would interefere with the smaller SnapDropZone collider inside it (or larger SDZ collider around it), it may need some bespoke implementation

Personally i'd like the SDZ's collider to be at least interactable with the pointer and be able to add an `InteractableObject` to the same GameObject the SDZ is on.

but if it's not easily feasible then let's close.

thanks

**Comment by thestonefox** [comment] 2019-04-02 07:31
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:31 UTC
Labels: unconfirmed bug
