### ISSUE TITLE
VRTK misbehaves in multi-scene setups if the VRTK scene is not the active one

### ISSUE THREAD

**Issue by krzys-h** [ExtendRealityLtd/VRTK#1956] opened 2019-03-12 16:36 UTC
I have a setup very similar to https://github.com/thestonefox/VRTK/issues/1580#issuecomment-341382739 where I put VRTK and main game logic in one scene, and the graphical environment made by our artists in another. To get Unity to use the lighting from the environment scene, that scene needs to be selected as active. The difference in my setup is that the environment scene needs to be changed at runtime, and since it's set as active, it's the default scene for newly instantiated objects and unloading it destroys some helper objects VRTK drops there.

### Environment

 * Source of VRTK: GitHub
 * Version of VRTK: 3.3.0 bf584452ff8df5f5fd71ae148b642131b5820fb7
 * Version of Unity3D: 2018.3.5f1
 * Hardware used: tried on a few different ones, not really relevant to the issue
 * SDK used: SteamVR

### Steps to reproduce

1. Create a new, empty scene. Remove the default objects.
2. Open `LegacyExamples/003_Controller_SimplePointer.unity` additively (it's under the right-click menu)
3. Move `[VRTK_SDKManager]`, `[VRTK_Scripts]` and `[ExampleSceneScripts]` to the new scene. This will be the VRTK / game logic scene.
4. Leave `WorldObjects`, `Floor`, and `Directional Light` in the example scene. This will represent the environment scene.
5. Set the environment scene as active (right-click -> Set Active Scene)
6. Click play in the editor

### Expected behavior

VRTK keeps its helper objects in the scene it was created in

### Current behavior

VRTK drops helper objects in the active scene, causing issues if you need to unload it at runtime

![image](https://user-images.githubusercontent.com/1517255/54216336-c08c4e00-44e9-11e9-85a1-870f2d14d802.png)

### Possible workaround

Reinitializing VRTK manually when changing the active scene seems to work:
```csharp
    yield return SceneManager.LoadSceneAsync(sceneToLoad, new LoadSceneParameters() { loadSceneMode = LoadSceneMode.Additive });
    if (previousScene.HasValue)
    {
        VRTK_SDKManager vrtkManager = FindObjectOfType<VRTK_SDKManager>();
        vrtkManager.UnloadSDKSetup();
        yield return SceneManager.UnloadSceneAsync(previousScene.Value);
        vrtkManager.TryLoadSDKSetupFromList();
    }
    SceneManager.SetActiveScene(sceneConfig.gameObject.scene);
```
I also had to disable playareaSync in VRTK_SDKSetupSwitcher, otherwise it fails with NullReferenceException when trying to reinitialize.

### Possible fix

Call `SceneManager.MoveGameObjectToScene(newObj, vrtkManager.scene)` every time VRTK instantiates a new root game object (i.e. one that is not parented to anything that already exists in the scene), or spawn it as parented to some VRTK object and only then call `SetParent(null)` (this will spawn it in the correct scene and then move it to the root of that scene). I could make a pull request which does this, but I'm a bit afraid that somebody is going to forget about it sooner or later and reintroduce this bug.

**Comment by thestonefox** [comment] 2019-03-29 18:15
Closing this as it's releated to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:15 UTC
