### ISSUE TITLE
[feature] Add new device for direction: Currently Locomoting Controller

### ISSUE THREAD

**Issue by 01271** [ExtendRealityLtd/VRTK#1671] opened 2017-12-22 23:06 UTC
It would be good to add a new small feature for locomotion.
Device for direction:
Headset
Left Controller
Right Controller
**Currently locomoting controller**

This would be taking the controller that was last touched on to initiate movement as the one that determines direction.

Example: I start touching and walking with the left controller. The left controller determines the direction I'm going. Then I stop and start touching and walking with the right controller. It no longer makes sense for the left controller to have bearing on my direction so it's no longer doing it. The right controller determines direction.

This is useful for games in which either or both controllers are used for direction.

**Comment by thestonefox** [comment] 2019-04-02 07:36
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:36 UTC
Labels: feature
