### ISSUE TITLE
simulator hand positions reset to hard-coded transform position

### ISSUE THREAD

**Issue by ezavesky** [ExtendRealityLtd/VRTK#1843] opened 2018-06-28 11:50 UTC
### Environment
This issue occurs on Github (and other) versions https://github.com/thestonefox/VRTK/blob/73273f3dba3530a1ef30bc9c3e44faa6c2c6e8ba/Assets/VRTK/Source/SDK/Simulator/SDK_InputSimulator.cs#L463 within Unity 2017.3.03f using the VRTK simulator.

### Steps to reproduce
1. Configure VRTK to use simulator environment.  Move either `LeftHand` or `RightHand` objects within theh `[VRSimualtor_CameraRig]` to different Y offset within the transform editor.  
2. Play the scene and observe that at first hand positions are valid.
3. Switch back and forth (possibly with default `alt` keyboard button) between HMD and hand movement.
4. Observe that the hand positions are reset to a hard-coded Y offset.

### Expected behavior
One may expect that while hands are reset (using the **Reset Hands At Switch** parameter on the `SDK_Input Simulator` script), they should be reset to the previous transform positions and not a fixed constant.

### Current behavior
Probably because there wasn't a need to alter player position/size, no caching of the hand transform position was ever performed.  Currently a hard-coded value is set for a transform [at this line](https://github.com/thestonefox/VRTK/blob/73273f3dba3530a1ef30bc9c3e44faa6c2c6e8ba/Assets/VRTK/Source/SDK/Simulator/SDK_InputSimulator.cs#L463).

**Comment by thestonefox** [comment] 2019-03-30 11:20
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:20 UTC
Labels: bug
