### ISSUE TITLE
InteractObjectHighlighter selects wrong material when used on objects with Unity3D's TrailRenderer

### ISSUE THREAD

**Issue by jkotlarek** [ExtendRealityLtd/VRTK#1836] opened 2018-06-20 04:39 UTC
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0
 * Version of Unity3D (e.g. Unity 5.4.4f1)
Unity 2018.2.0b9
 * Hardware used (e.g. Vive/Oculus)
Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR

### Steps to reproduce

In Editor:
Add an InteractTouch script to the controller.
Create a GameObject with a material (i.e. a primitive sphere)
Add an InteractableObject script to the GameObject
Add an InteractObjectHighlighter script to the same GameObject
Add a TrailRenderer to the same GameObject
*Add a material to the TrailRenderer, such as one of the defaults in the VRTK examples "Green.mat"
Change the Touch Highlight Color from black to any other color so you can see it.

Enter play mode:
Touch the GameObject with the Controller
Stop touching the GameObject with the Controller.

*Note: The step to add a material to the TrailRenderer is optional, and the bug is exhibited either way. However, adding a material clarifies the behavior somewhat.

### Expected behavior

When the controller is pulled away from the GameObject, the GameObject should have its old material reassigned to it, thus returning to its original color.

### Current behavior

When the controller is pulled away from the GameObject, the GameObject is assigned the material from its TrailRenderer. (With this set-up, the particle ends up being green, instead of gray).

**Comment by thestonefox** [comment] 2019-03-30 11:20
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:20 UTC
Labels: unconfirmed bug
