### ISSUE TITLE
Grab/Ungrab not being set up on a VRTK_PhysicsRotator when the VRTK_InteractableObject pre exists

### ISSUE THREAD

**Issue by bhermer** [ExtendRealityLtd/VRTK#1933] opened 2019-01-14 13:37 UTC
### Environment

Github
Github Master

### Steps to reproduce

Place a VRTK_InteractableObject on a game object which has a VRTK_PhysicsRotator

### Expected behavior

Regardless of if the VRTK_InteractableObject  is created at runtime or placed on at design time, the   ManageInteractableObjectListeners(true); should be called

### Current behavior

Listeners are not being set up when using a design time VRTK_InteractableObject , the   ManageInteractableObjectListeners(true); from line 377 needs to be moved out of the if statement:

```
    protected virtual void SetupInteractableObject()
        {
            createControlInteractableObject = false;
            controlInteractableObject = GetComponent<VRTK_InteractableObject>();
            if (controlInteractableObject == null)
            {
                controlInteractableObject = gameObject.AddComponent<VRTK_InteractableObject>();
                createControlInteractableObject = true;
                controlInteractableObject.isGrabbable = true;
                controlInteractableObject.ignoredColliders = (onlyInteractWith.Length > 0 ? VRTK_SharedMethods.ColliderExclude(GetComponentsInChildren<Collider>(true), VRTK_SharedMethods.GetCollidersInGameObjects(onlyInteractWith, true, true)) : new Collider[0]);

                SetupGrabMechanic();
                SetupSecondaryAction();
            }
                ManageInteractableObjectListeners(true);
        }
```

**Comment by thestonefox** [comment] 2019-03-29 18:15
Closing this as it's releated to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:15 UTC
