### ISSUE TITLE
BelzierPointerRenderer briefly displays a LineRenderer customer tracer in the wrong location

### ISSUE THREAD

**Issue by TheRealBobSmith** [ExtendRealityLtd/VRTK#1835] opened 2018-06-17 22:54 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.2.1 
 * Version of Unity3D: 2017.4.3f1
 * Hardware used: Oculus
 * SDK used: Oculus SDK

### Steps to reproduce

Use an Empty game object with a LineRenderer as a BelzierPointerRenderer's Customer Tracer for teleporting. Frequently when teleporting, the Belizer tracer will flash briefly pointing at an incorrect location before immediately updating to the proper location, i.e. where the cursor is.

More explicitly, by teleporting from point X to point Y, then attempting to teleport to point Z, the Belzier tracer will flash briefly pointing towards point X before updating and pointing correctly to point Z. In other words, the curve will still briefly reflect the previous X->Y curve before updating to the current Y->Z curve.

This appears (my guess) to be caused by BelzierPointerRenderer's ToggleRenderer() function calling TogglePointerTracer(pointerState, actualState) prior to the Belzier curve is calculated to the appropriate target. Commenting out the TogglePointerTracer() call eliminates the issue. 

Not sure if this part helps, but this issue appears to be specific to the LineRenderer. If I attach a Mesh Filter to the object with the LineRenderer, ONLY the line appears to exhibit this issue, while the associated mesh does not.

**Comment by thestonefox** [comment] 2019-03-30 11:20
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:20 UTC
