### ISSUE TITLE
Throwing not working properly

### ISSUE THREAD

**Issue by imperidal** [ExtendRealityLtd/VRTK#1801] opened 2018-05-17 03:48 UTC
### Environment

 * VRTK-master from Github
 * Unity 2018.1 and Unity 2017.3
 * Rift and GearVR
 * Oculus SDK

### Steps to reproduce

- Create a fresh project
- Import Oculus Utilities and VRTK-master
- Set up a floor and an interactable cube
- Set up controller with grabbing via pointer renderer (snaps to the controller, not to the tip of pointer)
- Grabbed the cube in-game and throw it around

### Expected behavior

The cube should have performed a throwing motion (like travel foward in a parabolic path).

### Current behavior

The cube just drops down.

I tried doing the same exact thing with VRTK 3.2.1 from store, and it works fine (with Rift).  Is there a way to make 3.2.1 work with GearVR (if theres no solution to this)?

**Comment by OddButAwesome** [comment] 2018-05-27 16:42
I thought it was just me. Going crazy testing w/ different combinations of versions of the plugins and Unity.

Can confirm this happens to me with Unity 5.65f1 & 2018.1.0f2 and the VRTK from GitHub as of 28/05/2018. Oculus Rift w/ touch. Attempts to throw result in object just dropping. 

Using 'Get Controller Velocity', 'Get Angular Velocity'  or 'Get Controller Velocity' returns 0,0,0 on the controller, the hand attach and the object being carried. Using Playmaker btw.

**Comment by bddckr** [comment] 2018-05-28 06:55
Try setting your physics time step to 1/90.

**Comment by OddButAwesome** [comment] 2018-05-29 11:43
I got it going. Not 100% sure which part made it work. But now I can throw objects. Will test physics (thanks for the suggest @bddckr) or maybe it was the new versions I installed. Rift / touch. 
- Unity 2017.4.3f1
- Unity2017.1.Playmaker.1.9.0.f5
- OVR Integration via Unity Store (previously I went to the Oculus site which was a version ahead of the store)
- VRTK via Unity Store (3.21 at the time i think)
- Playmaker 3x actions from Eric (Dumb Game Dev - great tutes btw)

Good luck!

**Comment by bddckr** [comment] 2018-05-29 11:55
VRTK from the Asset Store is very, very, **very** old. Use the GitHub master branch instead.

**Comment by OddButAwesome** [comment] 2018-05-29 12:36
Originally I downloaded the latest VRTK and OVR (SDK, Avatar & Utils) directly from Github and the Oculus website which had later versions. At some stage I will probably try upgrading the components listed above, including Unity. But for now I am just happy that it actually works.  The problem I face at present is the brick wall I have made from Unity cubes deform from bricks (scale 2,1,2) when I throw a cube at them int something resembling paralellograms. =D. Still, after 2 weeks of trying to solve the 'no throw' issue. I am a happy chappy.

**Comment by OddButAwesome** [comment] 2018-05-30 23:45
Updated to the latest VRTK into (copy of) the working project and it did the drop thing again. Haven't had a chance to try different OVR or Unity yet but something about the latest (GitHub) VRTK appears to be doing this on my setup.

**Comment by imperidal** [comment] 2018-07-23 03:52
Just to update.  Today (23 July 2018), I've updated my project to the latest Oculus Utilities (1.27), and updated VRTK to the latest master VRTK from github (was using VRTK from the store).  Also updated my Unity to 2018.1.7f1.

Everything works fine with VRTK so far.  No more throwing problems.  I'm planning to update Unity to 2018.2 in the future.  I hope everything goes well.

**Comment by imperidal** [comment] 2018-07-24 03:59
Nope.  Back to the problem.  I have no idea what to do now lol.

**Comment by thestonefox** [comment] 2019-04-02 07:30
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:30 UTC
