### ISSUE TITLE
isKinematic bug (race conditions)

### ISSUE THREAD

**Issue by subzero911** [ExtendRealityLtd/VRTK#1815] opened 2018-05-25 07:51 UTC
VRTK_InteractableObject piece of code:
![default](https://user-images.githubusercontent.com/12999702/40532152-33458b5a-6007-11e8-8f58-01a61185b330.png)
A code above looks wrong.
`interactableRigidbody = GetComponent<Rigidbody>();`
initialized in Awake.
But my script is initialized in Awake too (it's necessary) and tries to access your property.
`isKinematicOnStart = interactableObject.isKinematic;`
And there's no guarantee that your interactableRigidbody will not be Null.
So isKinematicOnStart accidentally can have a value of "true". And then my gameobject is set to kinematic when game begins.
I avoided it by accessing to Rigidbody component directly
`isKinematicOnStart = GetComponent<Rigidbody>().isKinematic;`

Suggestions:
if (interactableRigidbody is Null) try to initialize it in property and return isKinematic
if it's still null - return false by default and debuglog a warning

**Comment by thestonefox** [comment] 2018-05-25 13:21
You shouldn't be returning `false` by default

because that's saying the object is a non kinematic rigidbody which is saying it should be affected by physics. If anything `true` is more correct because you're saying this object either has a rigidbody or has no rigidbody and is not affected by physics (which is the same/similar to what a kinematic rigidbody is)

**Comment by subzero911** [comment] 2018-05-25 14:16
I just want to say that it leads to incorrect situation when I get `isKinematic = true;` while actual `Rigidbody.isKinematic` is false.

**Comment by thestonefox** [comment] 2018-05-25 14:19
but if it was the other way round and it returned `false` but the rigidbody was `true` then it would set it to the wrong result again.

**Comment by subzero911** [comment] 2018-05-25 14:26
Then it's better to perform an additional check:

```if (interactionalRigidbody != null)
{
	return interactionalRigidbody.isKinematic;
}
else
{
	interactionalRigidbody = GetComponent<Rigidbody>();
	if (interactionalRigidbody)
		return interactionalRigidbody.isKinematic;
	else Debug.LogError("...");
}```

**Comment by thestonefox** [comment] 2018-05-25 14:27
that's not going to help your race condition though is it? isn't that just going to always throw an error for you?

**Comment by subzero911** [comment] 2018-05-25 18:36
No, it never should throw an error.
Because when I access the property from the other script's Awake(), interactionalRigidbody may be not initialized yet.
When I force it to initialize (GetComponent), it definitely won't be Null.

**Comment by thestonefox** [comment] 2019-04-02 07:30
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:30 UTC
