### ISSUE TITLE
VRTK_TouchpadControl don`t work

### ISSUE THREAD

**Issue by du814175594** [ExtendRealityLtd/VRTK#1968] opened 2019-03-30 11:06 UTC
Environment
Source of VRTK: Unity Asset Store
Version of VRTK: 3.3.0
Version of Unity3D: 2017.2.1f1
Hardware used: Vive
SDK used: UnityXR,
Steps to reproduce
First I imported the latest SteamVR, then imported the latest VRTK, and finally entered the example scene [006 - Locomotion] MovementTypes.I looked at the code and felt that I should be able to move, and the first few scenes were normal.
Expected behavior
I should be able to move with the touchpad

Current behavior
I can't move with the touchpad

**Comment by thestonefox** [comment] 2019-04-02 07:29
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:29 UTC
