### ISSUE TITLE
Bug: VRTK_UIPointer Doesn't Disable If Covered by Screen Space Canvas

### ISSUE THREAD

**Issue by fredwgreene** [ExtendRealityLtd/VRTK#1197] opened 2017-05-14 05:18 UTC
**Expected Behavior:**
VRTK_UIPointer always disables properly when leaving a VRTK Worldspace UI when using VRTK_Pointer.Toggle(false) in a callback from registered event VRTK_UIPointer.UIPointerElementExit;

**Current Behavior:**
The VRTK_UIPointer doesn't properly deactivate when there is a Screen Space Canvas overlapping with where the UI Pointer is pointing on the World Space VRTK canvas when it leaves the canvas. This is causing the VRTK_UIPointer.UIPointerElementExit event not be Invoked and thus the pointer doesn't get Toggle(false) called even though the pointer has left the World Space VRTK canvas.

**Environment:**
VRTK 3.1.0 (Github) - downloaded 5/12/17
Unity 5.5.2f1
Either Vive/Oculus

**Steps to Reproduce:**
1. Open example scene 34 (interacting with Unity UI)
2. Check VRTK_ControllerUIPointerEvents_ListenerExample's [TogglePointerOnHit] -> [True]
3. Set VRTK_Pointer and VRTK_UIPointer's [Activation Button] -> [Undefined]
4. Set VRTK_Pointer's [Enable Teleport] -> [False]
5. Add a large button (like 1/4 screen size?) in the center of a new Screen Space canvas (or you can use SDK Setup Switcher canvas).
6. Hit Play (At this point the Pointer should only show when pointing at WorldSpace VRTK UI elements.)
7. Point the pointer at a VRTK WorldSpace UI and bring it past the edge of the World Space Canvas. If the Screen Space button you added in Step 5 is covering the point (on the monitor) where the pointer leaves the WorldSpace Canvas, the pointer will remain active (red now since it isn't pointing at anything it can interact with).

**Comment by thestonefox** [comment] 2017-05-14 09:26
@bddckr I think we need to re-look into the new UI system where we allow for both VR controller and on screen mouse raycasters.

I think they are conflicting with each other.

**Comment by thestonefox** [comment] 2017-05-14 09:27
Or maybe we can do something in the VRTK caster that ignores anything that isn't on a worldspace canvas?

**Comment by JWNJWN** [comment] 2018-06-15 17:01
I cannot reproduce this bug.
Can you please try on the latest master and get back to us?

**Comment by thestonefox** [comment] 2019-04-02 07:29
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:29 UTC
Labels: bug, w_bug
