### ISSUE TITLE
highlight not working in build but in editor

### ISSUE THREAD

**Issue by nbac** [ExtendRealityLtd/VRTK#1829] opened 2018-06-10 19:09 UTC
### Environment

 * Source of VRTK Github
 * Version of VRTK Github master 3.2.1
 * Version of Unity3D 2018.1.0f2
 * SDK used Oculus Utilities

### Steps to reproduce

use a object with standart shader and a high metallic valued texture in the metallic slot

### Expected behavior

in editor the higlight material is very bright and noticeable even in a very dark scene with just on light source. (the highlight material is unlit?)

### Current behavior

in build the highlighting is almost not visible just in areas where i get reflections on grabbable object. it seems to not overwrite the emissive value with the highlight color!? or it is not using a unlit shader!?
as soon as i build without metallic map on object it works in build too.

**Comment by christo-auer** [comment] 2018-10-12 08:20
I had the same behaviour. Activating the "Emissive" option in the material (using Standard shader) fixed the issue for me.

**Comment by thestonefox** [comment] 2019-03-30 11:21
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:21 UTC
Labels: unconfirmed bug
