### ISSUE TITLE
Cannot reverse artificial slider direction

### ISSUE THREAD

**Issue by mindrend** [ExtendRealityLtd/VRTK#1903] opened 2018-09-19 19:22 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK" v 3.3.0
 * Version of Unity3D: 2018.2.6f1
 * Hardware used: HTC Vive
 * SDK used: SteamVR

### Steps to reproduce

In the Interactions Demo scene, change the value of the artificial slider control from a positive value to a negative value

### Expected behavior

The slider should travel in the opposite direction

### Current behavior

The slider remains moving in the same direction

### Additional observations

It appears that the slider can only move in the positive direction of the operate axis. Setting a negative stroke value should make the slider move in the negative direction relative to the parent but it still moves positive no matter what.

**Comment by thestonefox** [comment] 2019-03-29 18:17
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:17 UTC
