### ISSUE TITLE
Feature Request - Freeze Rotation/position on transform follow

### ISSUE THREAD

**Issue by wimachtendink** [ExtendRealityLtd/VRTK#1837] opened 2018-06-21 00:48 UTC
Hello,

I would like for the transform follow component to allow for following only certain axes

The closest thing I saw to this feature request was this https://github.com/thestonefox/VRTK/pull/1549

Rather than following on all axes, I would like to be able to select specific rotational axes to follow similar to the FreezeRotation constraints provided by Unity's Rigidbody component.

In testing an alpha of my project I have a menu following the headset to keep the start menu right in front of the user. To read or select menu items my users were tilting their heads up and down causing the menu to follow up and down leading to this confusing and very slightly embarrassing dance where they try to position their head and point with their controller.

What I would like to do is rotate only following the Y axis, as I don't really need x or z rotation. 

Thank you for your time

**Comment by bddckr** [comment] 2018-06-21 08:04
Hey there!

I believe this is a good feature addition and will look into it for version 4 in the future.

Until then you can subclass TransformFollow and override `SetPositionOnGameObject` to customize and only set the axes you want to change!

Additionally I recommend to join our [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) as it's way easier to discuss stuff like this. We prefer to only get bug reports here on GitHub Issues, thanks!

**Comment by thestonefox** [comment] 2019-03-30 11:20
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:20 UTC
