### ISSUE TITLE
Incorrect 'Valid Drop' behavior after grabbing from drop zones placed close to each other

### ISSUE THREAD

**Issue by NOT-Lonely** [ExtendRealityLtd/VRTK#1857] opened 2018-07-22 07:42 UTC
### Environment

 * VRTK 3.3.0 GitHub master
 * Tested with Unity 2017.4, 2018.1, 2018.2
 * Vive
 * SteamVR

### Steps to reproduce

1. Open [005 - Interactions] InteractableObjects demo scene;
2. Copy the saucer snap drop zone few times and place them close to each other;
3. Enter Play Mode and try to put the saucer to any of these drop zones and then grab it from the drop zone;
4. Release the grab button.

![image](https://user-images.githubusercontent.com/41533634/43043394-59ef73ce-8dac-11e8-8864-b2dc38bddf40.png)

### Expected behavior

The unsnapped saucer has to be still grabbed by the controller after releasing the grab button, because this behavior is set in the saucer InteractableObject settings (drop valid snap drop zones)

### Current behavior

When you unsnap the saucer object from the snap drop zone, it's falling down (ungrabbing) after releasing the controller grab button.

**Comment by thestonefox** [comment] 2019-03-30 11:18
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:18 UTC
