### ISSUE TITLE
UI elements do not properly react to pointer

### ISSUE THREAD

**Issue by finartist** [ExtendRealityLtd/VRTK#1919] opened 2018-11-08 12:23 UTC
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (master  80db756)
 * Version of Unity3D (2017.4.13f1)

### Steps to reproduce
- open example scene [007 - Interactions] InteractionHelpers
- use the pointer to hover over the buttons in the scroll view
- similar on the dropdown if you want to chose an option 

### Expected behavior
- the button, which the pointer hits currently, is highlighted

### Current behavior
-  only the first button hit in the scrollview or no button is highlighted
- if clicked on the button, it will stay in the highlighed/hoverd state, even if the pointer is moved off the button and the trigger is released
- or the button cannot be pressed at all
(see picture, for better visibility, the button is supposed to be yellow but isn't)

![image](https://user-images.githubusercontent.com/15245377/48198479-47bd8f80-e359-11e8-9458-6941331e4606.png)

(Edit: possible duplicate of #1709)

**Comment by finartist** [comment] 2018-11-08 12:33
This seems to related to issue #1542, because removing line 140
`target = (target == null ? result.gameObject : target);`

 in VRTK_VRInputModule introduced in  this commit (commit bc02cfae0218aa93a9fc740d36aece1cdcdd164f) kind of solves the issue for me. I haven't checked if the behaviour from issue #1542 / #1543 occurs again.

**Comment by Bamfax** [comment] 2019-01-06 22:16
I also experienced this issue and the proposed fix/workaround described by finartist (uncommenting line 140 in VRTK_VRInputModule) helped. Finartist, thank you very much for pointing that out.

**Comment by neuman** [comment] 2019-02-15 18:57
I am experiencing this in the current version, and commenting out line 140 did not help. Has there been any progress on this bug, or is there a workaround?

**Comment by thestonefox** [comment] 2019-03-29 18:16
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:16 UTC
