### ISSUE TITLE
UIPointerElementExit is not called when disabling VRTK_UICanvas component

### ISSUE THREAD

**Issue by vcbnm** [ExtendRealityLtd/VRTK#1849] opened 2018-07-05 10:03 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK: d88c9ea
 * Version of Unity3D: Unity 2018.1.4f1
 * Hardware used: HTC Vive Pro
 * SDK used: Steam VR v1.2.3

### Steps to reproduce

1. Open the scene of Example 007.
2. Create a new canvas, set Render mode to World space, set scale to 0.001, width/height to 1000/800.
3. Add VRTK_UICanvas and Canvas Group components, use default settings.
4. Add a button as a child to the canvas, set the width and height to make it easy to target, otherwise use default settings.
5. In the button text, disable Raycast Target to prevent side-effects.
6. Create and add a new empty script on the canvas object.
7. In the script, Create a void function that disables the VRTK_UICanvas component. I started a coroutine to re-enable the canvas component again after a few seconds.
8. On the button OnClick event, point towards the function.
9. Disable or delete all other canvas objects to prevent overlap.
10. Play the scene, make sure that that you can easily aim the pointer on the button and click to disable the VRTK_UICanvas. Make sure you look in the same direction as the canvas.

Optionally call a debug message on ElementExit and Enter.

### Expected behavior

When disabling the VRTK_UICanvas, UIPointer_ElementExit should be called because there is no longer a valid element to hit. When enabling again, ElementEnter is invoked because there is a valid UI hit again.

### Current behavior

When disabling the VRTK_UICanvas, UIPointer_ElementExit is never called. The event is only called when looking away from the canvas while or after disabling the canvas. However, ElementEnter does invoke when enabling the canvas in front of the UIPointer.

### Possible solution

When disabling a VRTK_UICanvas, check if any UIPointer raycast has a hit on the canvas and call ElementExit on it.

**Comment by thestonefox** [comment] 2019-03-30 11:19
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:19 UTC
