### ISSUE TITLE
Outline Object Highlighter Use All Attached MeshRenderers

### ISSUE THREAD

**Issue by SK83RJOSH** [ExtendRealityLtd/VRTK#1028] opened 2017-03-16 12:15 UTC
We recently got the option to specify what GameObjects/MeshRenderers should be used when highlighting an object, which is awesome! I'd love to have a checkbox to auto populate this list from all attached MeshRenderers though, since this seems like a pretty common use case. 😄

**Comment by theanimator** [comment] 2017-12-04 19:28
Anyone have a multi-mesh asset that would be good to test before and after my changes? Otherwise I'll just dig something up.

**Comment by thestonefox** [comment] 2019-04-02 07:38
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:38 UTC
Labels: enhancement, w_feature
