### ISSUE TITLE
Body Physics/Leaning and Touchpad Walking Enhancement

### ISSUE THREAD

**Issue by sbmhome** [ExtendRealityLtd/VRTK#1423] opened 2017-08-13 22:58 UTC
The current setup allows for leaning when the touchpad is not touched by turning the VRTK_BodyCollider to isTrigger. This allows the Body Collider to pass thru a table or wall to simulate leaning.

There are two current issues.

1. You can't lean while touching the touchpad.
2. If you do go into geometry, If you touch the touchpad...you will be forced away from the table or wall once the BodyCollider goes back to isTrigger = false;

I suggest the following.

1. Keep the BodyCollider is Trigger = false at all times.

2. If the player is colliding with a table....move the BodyCollider GameObject's localPosition away from Vector3.zero as the player moves (in real life) within their play area. This will keep the BodyCollider GO out of any scene geometry , while the headset goes over a table...so they will be separate. This would give the player the ability to still move with the touchpad (along the path of the geometry)...even if they are slightly over geometry (This could possibly avoid a stuttering scenario).

3. If the player's headset goes too far (this can be adjustable)....then the touch pad control stops working altogether. This will force the player to move away from the geometry (by walking in real life).

4. As the person get closer to the tables Collider edge, the distance from the Head set and BodyCollider will then shrink....(and ultimately get back to Vector3.zero).

I've been thinking about this over the past few days...would love to hear some feedback to see if this solution is viable.

**Comment by thestonefox** [comment] 2017-08-14 08:01
If you have the body collider trigger = false all the time then you'll never be able to walk through things or lean over things.

But now we have 2 body colliders (1 for the foot and 1 for the body) i wonder if the foot collider is switched to trigger on movement that would enable leaning.

**Comment by thestonefox** [comment] 2017-08-15 17:09
Just to update with @jwnjwn 's suggestion from slack.

if we know the velocity of the collider, we can determine they can lean if their velocity is 0 as they are probably bumping into something preventing them from moving. However, they could still have a sideway velocity, so we'd need to only take into consideration the velocity towards the direction of the colliding object.

**Comment by thestonefox** [comment] 2019-04-02 07:37
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:37 UTC
Labels: enhancement, w_feature

**Comment by sbmhome** [comment] 2019-04-02 08:00
Yea please close.

I’ve been deep into development of my game. The Days After and I just noticed that VRTK got a grant from Oculus....that’s awesome, congrats!

I’ll use VRTK 4 for my next project :).

Regards,
Steve
