### ISSUE TITLE
VRTK_StraightPointerRenderer tracer None Update Transform Position and Rotation

### ISSUE THREAD

**Issue by LangTao92** [ExtendRealityLtd/VRTK#1853] opened 2018-07-13 02:22 UTC
The VRTK_StraightPointerRenderer  none  Update Transform Position and Rotation,please add
 
 Transform origin = GetOrigin();
+        actualContainer.transform.position = origin.position;
 +       actualContainer.transform.rotation = origin.rotation;
float objectInteractorScaleIncrease = 1.05f;
Because the 3.2.1 have these statement,but at 3.3.0 is missing,so the bug is that dynamic change ray origin Transform,but the  tracer is not correct rendered.

**Comment by thestonefox** [comment] 2019-03-30 11:18
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-30 11:18 UTC
