### ISSUE TITLE
Can't set distance field of NavMeshData

### ISSUE THREAD

**Issue by rockwalrus** [ExtendRealityLtd/VRTK#1930] opened 2018-12-27 21:46 UTC
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.3.0
 * Version of Unity3D:2018.2.6f1
 * SDK used: WMR

### Steps to reproduce

Create a gameobject with a `NavMeshData` component. Try to change "distance".

### Expected behavior

The distance field changes value.

### Current behavior

As soon as focus moves to a different field, it reverts to the original value.

See also https://forum.unity.com/threads/vrtk-navmeshdata-bug.532586/

**Comment by thestonefox** [comment] 2019-03-29 18:15
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-03-29 18:15 UTC
