### ISSUE TITLE
Canvas is not interacting

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [ExtendRealityLtd/VRTK#1710] opened 2018-01-19 04:49 UTC
### Environment

 * Source of VRTK (Package from old VRTK project)
 * Version of VRTK (2.1.0)
 * Version of Unity3D (Unity 5.6.2f1)
 * Hardware used (Vive)
 * SDK used (OpenVR/SteamVR)

### Steps to reproduce

I made  VRTK package from my old project and imported it my another project. Open 034_Controls_InteractingWithUnityUI scene from example folder but no canvas is interacting.

### Expected behavior

Canvas should be interacted.

### Current behavior

No canvas is interacting. I found that below components attaced with canvas dynamically. 
1. VRTK_IO Graphic raycaster attached
2. boxcollider
3. image Component

Apart from this problem, actually I am getting very strange behviour like 
1. In editor, if i click somewhere in hirarchy during runtime, then, UI stop interacting.
2. I have a dropdown, if i try to select it through controller pointer, it hardly able to select or sometime not selecting at all. If i move my position to left or right most, then i select the dropdown it working well.

**Comment by bddckr** [comment] 2018-01-19 08:55
VRTK 2.1.0 is 17 months old. There have been numerous releases since then. All of them include bugfixes.

No one reported any of the example scenes being broken on current releases.

I suggest to use [VRTK 3.3.0](https://github.com/thestonefox/VRTK/tree/release/3.3.0-alpha). For troubleshooting [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) is the support channel to use, not GitHub issues.

**Comment by ValooFX** [comment] 2018-01-25 11:01
I dont want to open another issue for this, but i had a similar problem with 3.2.1 where i found that only the collider was not setup correctly. I fixed this by delaying the SetupCanvas() in VRTK_UICanvas by a frame via a coroutine, because i was using the content size fitter and it apparently needs one frame to layout the GUI.

**Comment by thestonefox** [comment] 2018-01-25 11:03
Can someone try this in 3.3.0?

**Comment by MuhammadFaizanKhan** [comment] 2018-01-27 11:21
sure i want to use 3.3.0 but is there any migration guide available from VRTK 2.1.0 to 3.3.0?

**Comment by Xwil** [comment] 2018-10-23 08:07
> Can someone try this in 3.3.0?

I tried in 3.3.0 & 4.0 in Unity 2017.4.9 & 2018.2.7, example 007 won't work, canvas can't interact. But I created a new scene, things goes well.
I believe it's a big problem, because it has happend to me in 2 years ago.
Not a english speaker, sorry to my typo or grammer wrong.

**Comment by thestonefox** [comment] 2019-04-02 07:32
Closing this as it's related to an older version of VRTK (v3.3) the master branch is now on VRTK v4. Feel free to request to reopen if the issue is still present.

**Closed by thestonefox** 2019-04-02 07:32 UTC
Labels: unconfirmed bug, w_bug
